package com.ltkj.app.common.model;

public class BaseHashMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_hash_map.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_hash_map.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_hash_map.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_hash_map.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_hash_map.is_remove
     *
     * @mbggenerated
     */
    private String isRemove;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_hash_map.id
     *
     * @return the value of m_hash_map.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_hash_map.id
     *
     * @param id the value for m_hash_map.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_hash_map.type_name
     *
     * @return the value of m_hash_map.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_hash_map.type_name
     *
     * @param typeName the value for m_hash_map.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_hash_map.key
     *
     * @return the value of m_hash_map.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_hash_map.key
     *
     * @param key the value for m_hash_map.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_hash_map.value
     *
     * @return the value of m_hash_map.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_hash_map.value
     *
     * @param value the value for m_hash_map.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_hash_map.is_remove
     *
     * @return the value of m_hash_map.is_remove
     *
     * @mbggenerated
     */
    public String getIsRemove() {
        return isRemove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_hash_map.is_remove
     *
     * @param isRemove the value for m_hash_map.is_remove
     *
     * @mbggenerated
     */
    public void setIsRemove(String isRemove) {
        this.isRemove = isRemove == null ? null : isRemove.trim();
    }
}