package com.ltkj.app.common.model;

import java.math.BigDecimal;
import java.util.Date;

public class BookInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_code
     *
     * @mbggenerated
     */
    private String bookCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_name
     *
     * @mbggenerated
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_category
     *
     * @mbggenerated
     */
    private String bookCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_author
     *
     * @mbggenerated
     */
    private String bookAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_company
     *
     * @mbggenerated
     */
    private String bookCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_date
     *
     * @mbggenerated
     */
    private Date bookDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_price
     *
     * @mbggenerated
     */
    private BigDecimal bookPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_synopsis
     *
     * @mbggenerated
     */
    private String bookSynopsis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_sum
     *
     * @mbggenerated
     */
    private Integer bookSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_num
     *
     * @mbggenerated
     */
    private Integer bookNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.book_url
     *
     * @mbggenerated
     */
    private String bookUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.Is_Active
     *
     * @mbggenerated
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.CREATE_DT
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.CREATE_OP
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.CREATE_PG
     *
     * @mbggenerated
     */
    private String createPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.UPDATE_DT
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.UPDATE_OP
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_book_info.UPDATE_PG
     *
     * @mbggenerated
     */
    private String updatePg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.uuid
     *
     * @return the value of q_book_info.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.uuid
     *
     * @param uuid the value for q_book_info.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_code
     *
     * @return the value of q_book_info.book_code
     *
     * @mbggenerated
     */
    public String getBookCode() {
        return bookCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_code
     *
     * @param bookCode the value for q_book_info.book_code
     *
     * @mbggenerated
     */
    public void setBookCode(String bookCode) {
        this.bookCode = bookCode == null ? null : bookCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_name
     *
     * @return the value of q_book_info.book_name
     *
     * @mbggenerated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_name
     *
     * @param bookName the value for q_book_info.book_name
     *
     * @mbggenerated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_category
     *
     * @return the value of q_book_info.book_category
     *
     * @mbggenerated
     */
    public String getBookCategory() {
        return bookCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_category
     *
     * @param bookCategory the value for q_book_info.book_category
     *
     * @mbggenerated
     */
    public void setBookCategory(String bookCategory) {
        this.bookCategory = bookCategory == null ? null : bookCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_author
     *
     * @return the value of q_book_info.book_author
     *
     * @mbggenerated
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_author
     *
     * @param bookAuthor the value for q_book_info.book_author
     *
     * @mbggenerated
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_company
     *
     * @return the value of q_book_info.book_company
     *
     * @mbggenerated
     */
    public String getBookCompany() {
        return bookCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_company
     *
     * @param bookCompany the value for q_book_info.book_company
     *
     * @mbggenerated
     */
    public void setBookCompany(String bookCompany) {
        this.bookCompany = bookCompany == null ? null : bookCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_date
     *
     * @return the value of q_book_info.book_date
     *
     * @mbggenerated
     */
    public Date getBookDate() {
        return bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_date
     *
     * @param bookDate the value for q_book_info.book_date
     *
     * @mbggenerated
     */
    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_price
     *
     * @return the value of q_book_info.book_price
     *
     * @mbggenerated
     */
    public BigDecimal getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_price
     *
     * @param bookPrice the value for q_book_info.book_price
     *
     * @mbggenerated
     */
    public void setBookPrice(BigDecimal bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_synopsis
     *
     * @return the value of q_book_info.book_synopsis
     *
     * @mbggenerated
     */
    public String getBookSynopsis() {
        return bookSynopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_synopsis
     *
     * @param bookSynopsis the value for q_book_info.book_synopsis
     *
     * @mbggenerated
     */
    public void setBookSynopsis(String bookSynopsis) {
        this.bookSynopsis = bookSynopsis == null ? null : bookSynopsis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_sum
     *
     * @return the value of q_book_info.book_sum
     *
     * @mbggenerated
     */
    public Integer getBookSum() {
        return bookSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_sum
     *
     * @param bookSum the value for q_book_info.book_sum
     *
     * @mbggenerated
     */
    public void setBookSum(Integer bookSum) {
        this.bookSum = bookSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_num
     *
     * @return the value of q_book_info.book_num
     *
     * @mbggenerated
     */
    public Integer getBookNum() {
        return bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_num
     *
     * @param bookNum the value for q_book_info.book_num
     *
     * @mbggenerated
     */
    public void setBookNum(Integer bookNum) {
        this.bookNum = bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.book_url
     *
     * @return the value of q_book_info.book_url
     *
     * @mbggenerated
     */
    public String getBookUrl() {
        return bookUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.book_url
     *
     * @param bookUrl the value for q_book_info.book_url
     *
     * @mbggenerated
     */
    public void setBookUrl(String bookUrl) {
        this.bookUrl = bookUrl == null ? null : bookUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.Is_Active
     *
     * @return the value of q_book_info.Is_Active
     *
     * @mbggenerated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.Is_Active
     *
     * @param isActive the value for q_book_info.Is_Active
     *
     * @mbggenerated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.CREATE_DT
     *
     * @return the value of q_book_info.CREATE_DT
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.CREATE_DT
     *
     * @param createDt the value for q_book_info.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.CREATE_OP
     *
     * @return the value of q_book_info.CREATE_OP
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.CREATE_OP
     *
     * @param createOp the value for q_book_info.CREATE_OP
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.CREATE_PG
     *
     * @return the value of q_book_info.CREATE_PG
     *
     * @mbggenerated
     */
    public String getCreatePg() {
        return createPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.CREATE_PG
     *
     * @param createPg the value for q_book_info.CREATE_PG
     *
     * @mbggenerated
     */
    public void setCreatePg(String createPg) {
        this.createPg = createPg == null ? null : createPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.UPDATE_DT
     *
     * @return the value of q_book_info.UPDATE_DT
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.UPDATE_DT
     *
     * @param updateDt the value for q_book_info.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.UPDATE_OP
     *
     * @return the value of q_book_info.UPDATE_OP
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.UPDATE_OP
     *
     * @param updateOp the value for q_book_info.UPDATE_OP
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_book_info.UPDATE_PG
     *
     * @return the value of q_book_info.UPDATE_PG
     *
     * @mbggenerated
     */
    public String getUpdatePg() {
        return updatePg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_book_info.UPDATE_PG
     *
     * @param updatePg the value for q_book_info.UPDATE_PG
     *
     * @mbggenerated
     */
    public void setUpdatePg(String updatePg) {
        this.updatePg = updatePg == null ? null : updatePg.trim();
    }
}