package com.ltkj.app.common.model;

import java.util.Date;

public class Cloth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.clo_name
     *
     * @mbggenerated
     */
    private String cloName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.clo_code
     *
     * @mbggenerated
     */
    private String cloCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.clo_brand
     *
     * @mbggenerated
     */
    private String cloBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.clo_price
     *
     * @mbggenerated
     */
    private Integer cloPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.clo_size
     *
     * @mbggenerated
     */
    private String cloSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.clo_color
     *
     * @mbggenerated
     */
    private String cloColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.Is_Active
     *
     * @mbggenerated
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.CREATE_DT
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.CREATE_OP
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.CREATE_PG
     *
     * @mbggenerated
     */
    private String createPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.UPDATE_DT
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.UPDATE_OP
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_cloth.UPDATE_PG
     *
     * @mbggenerated
     */
    private String updatePg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.id
     *
     * @return the value of q_cloth.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.id
     *
     * @param id the value for q_cloth.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.clo_name
     *
     * @return the value of q_cloth.clo_name
     *
     * @mbggenerated
     */
    public String getCloName() {
        return cloName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.clo_name
     *
     * @param cloName the value for q_cloth.clo_name
     *
     * @mbggenerated
     */
    public void setCloName(String cloName) {
        this.cloName = cloName == null ? null : cloName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.clo_code
     *
     * @return the value of q_cloth.clo_code
     *
     * @mbggenerated
     */
    public String getCloCode() {
        return cloCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.clo_code
     *
     * @param cloCode the value for q_cloth.clo_code
     *
     * @mbggenerated
     */
    public void setCloCode(String cloCode) {
        this.cloCode = cloCode == null ? null : cloCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.clo_brand
     *
     * @return the value of q_cloth.clo_brand
     *
     * @mbggenerated
     */
    public String getCloBrand() {
        return cloBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.clo_brand
     *
     * @param cloBrand the value for q_cloth.clo_brand
     *
     * @mbggenerated
     */
    public void setCloBrand(String cloBrand) {
        this.cloBrand = cloBrand == null ? null : cloBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.clo_price
     *
     * @return the value of q_cloth.clo_price
     *
     * @mbggenerated
     */
    public Integer getCloPrice() {
        return cloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.clo_price
     *
     * @param cloPrice the value for q_cloth.clo_price
     *
     * @mbggenerated
     */
    public void setCloPrice(Integer cloPrice) {
        this.cloPrice = cloPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.clo_size
     *
     * @return the value of q_cloth.clo_size
     *
     * @mbggenerated
     */
    public String getCloSize() {
        return cloSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.clo_size
     *
     * @param cloSize the value for q_cloth.clo_size
     *
     * @mbggenerated
     */
    public void setCloSize(String cloSize) {
        this.cloSize = cloSize == null ? null : cloSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.clo_color
     *
     * @return the value of q_cloth.clo_color
     *
     * @mbggenerated
     */
    public String getCloColor() {
        return cloColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.clo_color
     *
     * @param cloColor the value for q_cloth.clo_color
     *
     * @mbggenerated
     */
    public void setCloColor(String cloColor) {
        this.cloColor = cloColor == null ? null : cloColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.description
     *
     * @return the value of q_cloth.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.description
     *
     * @param description the value for q_cloth.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.Is_Active
     *
     * @return the value of q_cloth.Is_Active
     *
     * @mbggenerated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.Is_Active
     *
     * @param isActive the value for q_cloth.Is_Active
     *
     * @mbggenerated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.CREATE_DT
     *
     * @return the value of q_cloth.CREATE_DT
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.CREATE_DT
     *
     * @param createDt the value for q_cloth.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.CREATE_OP
     *
     * @return the value of q_cloth.CREATE_OP
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.CREATE_OP
     *
     * @param createOp the value for q_cloth.CREATE_OP
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.CREATE_PG
     *
     * @return the value of q_cloth.CREATE_PG
     *
     * @mbggenerated
     */
    public String getCreatePg() {
        return createPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.CREATE_PG
     *
     * @param createPg the value for q_cloth.CREATE_PG
     *
     * @mbggenerated
     */
    public void setCreatePg(String createPg) {
        this.createPg = createPg == null ? null : createPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.UPDATE_DT
     *
     * @return the value of q_cloth.UPDATE_DT
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.UPDATE_DT
     *
     * @param updateDt the value for q_cloth.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.UPDATE_OP
     *
     * @return the value of q_cloth.UPDATE_OP
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.UPDATE_OP
     *
     * @param updateOp the value for q_cloth.UPDATE_OP
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_cloth.UPDATE_PG
     *
     * @return the value of q_cloth.UPDATE_PG
     *
     * @mbggenerated
     */
    public String getUpdatePg() {
        return updatePg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_cloth.UPDATE_PG
     *
     * @param updatePg the value for q_cloth.UPDATE_PG
     *
     * @mbggenerated
     */
    public void setUpdatePg(String updatePg) {
        this.updatePg = updatePg == null ? null : updatePg.trim();
    }
}