package com.ltkj.app.common.model;

import java.util.Date;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Company_Id
     *
     * @mbggenerated
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Company_Name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Company_Name_E
     *
     * @mbggenerated
     */
    private String companyNameE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Short_Name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Short_Name_E
     *
     * @mbggenerated
     */
    private String shortNameE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Alpha_Cd
     *
     * @mbggenerated
     */
    private String alphaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Legal_Person
     *
     * @mbggenerated
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Register_Code
     *
     * @mbggenerated
     */
    private String registerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.Is_Active
     *
     * @mbggenerated
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CREATE_DT
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CREATE_OP
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.CREATE_PG
     *
     * @mbggenerated
     */
    private String createPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.UPDATE_DT
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.UPDATE_OP
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_company.UPDATE_PG
     *
     * @mbggenerated
     */
    private String updatePg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.uuid
     *
     * @return the value of sys_company.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.uuid
     *
     * @param uuid the value for sys_company.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Company_Id
     *
     * @return the value of sys_company.Company_Id
     *
     * @mbggenerated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Company_Id
     *
     * @param companyId the value for sys_company.Company_Id
     *
     * @mbggenerated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Company_Name
     *
     * @return the value of sys_company.Company_Name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Company_Name
     *
     * @param companyName the value for sys_company.Company_Name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Company_Name_E
     *
     * @return the value of sys_company.Company_Name_E
     *
     * @mbggenerated
     */
    public String getCompanyNameE() {
        return companyNameE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Company_Name_E
     *
     * @param companyNameE the value for sys_company.Company_Name_E
     *
     * @mbggenerated
     */
    public void setCompanyNameE(String companyNameE) {
        this.companyNameE = companyNameE == null ? null : companyNameE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Short_Name
     *
     * @return the value of sys_company.Short_Name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Short_Name
     *
     * @param shortName the value for sys_company.Short_Name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Short_Name_E
     *
     * @return the value of sys_company.Short_Name_E
     *
     * @mbggenerated
     */
    public String getShortNameE() {
        return shortNameE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Short_Name_E
     *
     * @param shortNameE the value for sys_company.Short_Name_E
     *
     * @mbggenerated
     */
    public void setShortNameE(String shortNameE) {
        this.shortNameE = shortNameE == null ? null : shortNameE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Alpha_Cd
     *
     * @return the value of sys_company.Alpha_Cd
     *
     * @mbggenerated
     */
    public String getAlphaCd() {
        return alphaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Alpha_Cd
     *
     * @param alphaCd the value for sys_company.Alpha_Cd
     *
     * @mbggenerated
     */
    public void setAlphaCd(String alphaCd) {
        this.alphaCd = alphaCd == null ? null : alphaCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Legal_Person
     *
     * @return the value of sys_company.Legal_Person
     *
     * @mbggenerated
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Legal_Person
     *
     * @param legalPerson the value for sys_company.Legal_Person
     *
     * @mbggenerated
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Register_Code
     *
     * @return the value of sys_company.Register_Code
     *
     * @mbggenerated
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Register_Code
     *
     * @param registerCode the value for sys_company.Register_Code
     *
     * @mbggenerated
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.Is_Active
     *
     * @return the value of sys_company.Is_Active
     *
     * @mbggenerated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.Is_Active
     *
     * @param isActive the value for sys_company.Is_Active
     *
     * @mbggenerated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CREATE_DT
     *
     * @return the value of sys_company.CREATE_DT
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CREATE_DT
     *
     * @param createDt the value for sys_company.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CREATE_OP
     *
     * @return the value of sys_company.CREATE_OP
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CREATE_OP
     *
     * @param createOp the value for sys_company.CREATE_OP
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.CREATE_PG
     *
     * @return the value of sys_company.CREATE_PG
     *
     * @mbggenerated
     */
    public String getCreatePg() {
        return createPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.CREATE_PG
     *
     * @param createPg the value for sys_company.CREATE_PG
     *
     * @mbggenerated
     */
    public void setCreatePg(String createPg) {
        this.createPg = createPg == null ? null : createPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.UPDATE_DT
     *
     * @return the value of sys_company.UPDATE_DT
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.UPDATE_DT
     *
     * @param updateDt the value for sys_company.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.UPDATE_OP
     *
     * @return the value of sys_company.UPDATE_OP
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.UPDATE_OP
     *
     * @param updateOp the value for sys_company.UPDATE_OP
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_company.UPDATE_PG
     *
     * @return the value of sys_company.UPDATE_PG
     *
     * @mbggenerated
     */
    public String getUpdatePg() {
        return updatePg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_company.UPDATE_PG
     *
     * @param updatePg the value for sys_company.UPDATE_PG
     *
     * @mbggenerated
     */
    public void setUpdatePg(String updatePg) {
        this.updatePg = updatePg == null ? null : updatePg.trim();
    }
}