package com.ltkj.app.common.model;

public class GeBytearray {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.ID_
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.REV_
     *
     * @mbggenerated
     */
    private Integer rev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.NAME_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    private String deploymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.GENERATED_
     *
     * @mbggenerated
     */
    private Byte generated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.BYTES_
     *
     * @mbggenerated
     */
    private byte[] bytes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.ID_
     *
     * @return the value of act_ge_bytearray.ID_
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.ID_
     *
     * @param id the value for act_ge_bytearray.ID_
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.REV_
     *
     * @return the value of act_ge_bytearray.REV_
     *
     * @mbggenerated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.REV_
     *
     * @param rev the value for act_ge_bytearray.REV_
     *
     * @mbggenerated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.NAME_
     *
     * @return the value of act_ge_bytearray.NAME_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.NAME_
     *
     * @param name the value for act_ge_bytearray.NAME_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @return the value of act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.GENERATED_
     *
     * @return the value of act_ge_bytearray.GENERATED_
     *
     * @mbggenerated
     */
    public Byte getGenerated() {
        return generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.GENERATED_
     *
     * @param generated the value for act_ge_bytearray.GENERATED_
     *
     * @mbggenerated
     */
    public void setGenerated(Byte generated) {
        this.generated = generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.BYTES_
     *
     * @return the value of act_ge_bytearray.BYTES_
     *
     * @mbggenerated
     */
    public byte[] getBytes() {
        return bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.BYTES_
     *
     * @param bytes the value for act_ge_bytearray.BYTES_
     *
     * @mbggenerated
     */
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }
}