package com.ltkj.app.common.model;

public class GeProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_property.NAME_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_property.VALUE_
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_property.REV_
     *
     * @mbggenerated
     */
    private Integer rev;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_property.NAME_
     *
     * @return the value of act_ge_property.NAME_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_property.NAME_
     *
     * @param name the value for act_ge_property.NAME_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_property.VALUE_
     *
     * @return the value of act_ge_property.VALUE_
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_property.VALUE_
     *
     * @param value the value for act_ge_property.VALUE_
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_property.REV_
     *
     * @return the value of act_ge_property.REV_
     *
     * @mbggenerated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_property.REV_
     *
     * @param rev the value for act_ge_property.REV_
     *
     * @mbggenerated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }
}