package com.ltkj.app.common.model;

import java.math.BigDecimal;
import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.company_id
     *
     * @mbggenerated
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.spec
     *
     * @mbggenerated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.batch_code
     *
     * @mbggenerated
     */
    private String batchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.primary_category
     *
     * @mbggenerated
     */
    private String primaryCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.small_category
     *
     * @mbggenerated
     */
    private String smallCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.weight
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.pic_src
     *
     * @mbggenerated
     */
    private String picSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.buying_price
     *
     * @mbggenerated
     */
    private BigDecimal buyingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.selling_price1
     *
     * @mbggenerated
     */
    private BigDecimal sellingPrice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.selling_price2
     *
     * @mbggenerated
     */
    private BigDecimal sellingPrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.selling_price3
     *
     * @mbggenerated
     */
    private BigDecimal sellingPrice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.discount
     *
     * @mbggenerated
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.replenish
     *
     * @mbggenerated
     */
    private Integer replenish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.key_cd
     *
     * @mbggenerated
     */
    private String keyCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.Is_Active
     *
     * @mbggenerated
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.CREATE_DT
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.CREATE_OP
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.CREATE_PG
     *
     * @mbggenerated
     */
    private String createPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.UPDATE_DT
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.UPDATE_OP
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_goods.UPDATE_PG
     *
     * @mbggenerated
     */
    private String updatePg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.goods_id
     *
     * @return the value of s_goods.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.goods_id
     *
     * @param goodsId the value for s_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.company_id
     *
     * @return the value of s_goods.company_id
     *
     * @mbggenerated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.company_id
     *
     * @param companyId the value for s_goods.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.goods_name
     *
     * @return the value of s_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.goods_name
     *
     * @param goodsName the value for s_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.spec
     *
     * @return the value of s_goods.spec
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.spec
     *
     * @param spec the value for s_goods.spec
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.batch_code
     *
     * @return the value of s_goods.batch_code
     *
     * @mbggenerated
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.batch_code
     *
     * @param batchCode the value for s_goods.batch_code
     *
     * @mbggenerated
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.primary_category
     *
     * @return the value of s_goods.primary_category
     *
     * @mbggenerated
     */
    public String getPrimaryCategory() {
        return primaryCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.primary_category
     *
     * @param primaryCategory the value for s_goods.primary_category
     *
     * @mbggenerated
     */
    public void setPrimaryCategory(String primaryCategory) {
        this.primaryCategory = primaryCategory == null ? null : primaryCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.small_category
     *
     * @return the value of s_goods.small_category
     *
     * @mbggenerated
     */
    public String getSmallCategory() {
        return smallCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.small_category
     *
     * @param smallCategory the value for s_goods.small_category
     *
     * @mbggenerated
     */
    public void setSmallCategory(String smallCategory) {
        this.smallCategory = smallCategory == null ? null : smallCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.weight
     *
     * @return the value of s_goods.weight
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.weight
     *
     * @param weight the value for s_goods.weight
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.pic_src
     *
     * @return the value of s_goods.pic_src
     *
     * @mbggenerated
     */
    public String getPicSrc() {
        return picSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.pic_src
     *
     * @param picSrc the value for s_goods.pic_src
     *
     * @mbggenerated
     */
    public void setPicSrc(String picSrc) {
        this.picSrc = picSrc == null ? null : picSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.description
     *
     * @return the value of s_goods.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.description
     *
     * @param description the value for s_goods.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.buying_price
     *
     * @return the value of s_goods.buying_price
     *
     * @mbggenerated
     */
    public BigDecimal getBuyingPrice() {
        return buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.buying_price
     *
     * @param buyingPrice the value for s_goods.buying_price
     *
     * @mbggenerated
     */
    public void setBuyingPrice(BigDecimal buyingPrice) {
        this.buyingPrice = buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.selling_price1
     *
     * @return the value of s_goods.selling_price1
     *
     * @mbggenerated
     */
    public BigDecimal getSellingPrice1() {
        return sellingPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.selling_price1
     *
     * @param sellingPrice1 the value for s_goods.selling_price1
     *
     * @mbggenerated
     */
    public void setSellingPrice1(BigDecimal sellingPrice1) {
        this.sellingPrice1 = sellingPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.selling_price2
     *
     * @return the value of s_goods.selling_price2
     *
     * @mbggenerated
     */
    public BigDecimal getSellingPrice2() {
        return sellingPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.selling_price2
     *
     * @param sellingPrice2 the value for s_goods.selling_price2
     *
     * @mbggenerated
     */
    public void setSellingPrice2(BigDecimal sellingPrice2) {
        this.sellingPrice2 = sellingPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.selling_price3
     *
     * @return the value of s_goods.selling_price3
     *
     * @mbggenerated
     */
    public BigDecimal getSellingPrice3() {
        return sellingPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.selling_price3
     *
     * @param sellingPrice3 the value for s_goods.selling_price3
     *
     * @mbggenerated
     */
    public void setSellingPrice3(BigDecimal sellingPrice3) {
        this.sellingPrice3 = sellingPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.discount
     *
     * @return the value of s_goods.discount
     *
     * @mbggenerated
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.discount
     *
     * @param discount the value for s_goods.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.quantity
     *
     * @return the value of s_goods.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.quantity
     *
     * @param quantity the value for s_goods.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.replenish
     *
     * @return the value of s_goods.replenish
     *
     * @mbggenerated
     */
    public Integer getReplenish() {
        return replenish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.replenish
     *
     * @param replenish the value for s_goods.replenish
     *
     * @mbggenerated
     */
    public void setReplenish(Integer replenish) {
        this.replenish = replenish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.key_cd
     *
     * @return the value of s_goods.key_cd
     *
     * @mbggenerated
     */
    public String getKeyCd() {
        return keyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.key_cd
     *
     * @param keyCd the value for s_goods.key_cd
     *
     * @mbggenerated
     */
    public void setKeyCd(String keyCd) {
        this.keyCd = keyCd == null ? null : keyCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.Is_Active
     *
     * @return the value of s_goods.Is_Active
     *
     * @mbggenerated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.Is_Active
     *
     * @param isActive the value for s_goods.Is_Active
     *
     * @mbggenerated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.CREATE_DT
     *
     * @return the value of s_goods.CREATE_DT
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.CREATE_DT
     *
     * @param createDt the value for s_goods.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.CREATE_OP
     *
     * @return the value of s_goods.CREATE_OP
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.CREATE_OP
     *
     * @param createOp the value for s_goods.CREATE_OP
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.CREATE_PG
     *
     * @return the value of s_goods.CREATE_PG
     *
     * @mbggenerated
     */
    public String getCreatePg() {
        return createPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.CREATE_PG
     *
     * @param createPg the value for s_goods.CREATE_PG
     *
     * @mbggenerated
     */
    public void setCreatePg(String createPg) {
        this.createPg = createPg == null ? null : createPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.UPDATE_DT
     *
     * @return the value of s_goods.UPDATE_DT
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.UPDATE_DT
     *
     * @param updateDt the value for s_goods.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.UPDATE_OP
     *
     * @return the value of s_goods.UPDATE_OP
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.UPDATE_OP
     *
     * @param updateOp the value for s_goods.UPDATE_OP
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_goods.UPDATE_PG
     *
     * @return the value of s_goods.UPDATE_PG
     *
     * @mbggenerated
     */
    public String getUpdatePg() {
        return updatePg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_goods.UPDATE_PG
     *
     * @param updatePg the value for s_goods.UPDATE_PG
     *
     * @mbggenerated
     */
    public void setUpdatePg(String updatePg) {
        this.updatePg = updatePg == null ? null : updatePg.trim();
    }
}