package com.ltkj.app.common.model;

import java.util.Date;

public class HiAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.ID_
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.REV_
     *
     * @mbggenerated
     */
    private Integer rev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.USER_ID_
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.NAME_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.DESCRIPTION_
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.TYPE_
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.TASK_ID_
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.PROC_INST_ID_
     *
     * @mbggenerated
     */
    private String procInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.URL_
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.CONTENT_ID_
     *
     * @mbggenerated
     */
    private String contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_attachment.TIME_
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.ID_
     *
     * @return the value of act_hi_attachment.ID_
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.ID_
     *
     * @param id the value for act_hi_attachment.ID_
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.REV_
     *
     * @return the value of act_hi_attachment.REV_
     *
     * @mbggenerated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.REV_
     *
     * @param rev the value for act_hi_attachment.REV_
     *
     * @mbggenerated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.USER_ID_
     *
     * @return the value of act_hi_attachment.USER_ID_
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.USER_ID_
     *
     * @param userId the value for act_hi_attachment.USER_ID_
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.NAME_
     *
     * @return the value of act_hi_attachment.NAME_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.NAME_
     *
     * @param name the value for act_hi_attachment.NAME_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.DESCRIPTION_
     *
     * @return the value of act_hi_attachment.DESCRIPTION_
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.DESCRIPTION_
     *
     * @param description the value for act_hi_attachment.DESCRIPTION_
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.TYPE_
     *
     * @return the value of act_hi_attachment.TYPE_
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.TYPE_
     *
     * @param type the value for act_hi_attachment.TYPE_
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.TASK_ID_
     *
     * @return the value of act_hi_attachment.TASK_ID_
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.TASK_ID_
     *
     * @param taskId the value for act_hi_attachment.TASK_ID_
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.PROC_INST_ID_
     *
     * @return the value of act_hi_attachment.PROC_INST_ID_
     *
     * @mbggenerated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_attachment.PROC_INST_ID_
     *
     * @mbggenerated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.URL_
     *
     * @return the value of act_hi_attachment.URL_
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.URL_
     *
     * @param url the value for act_hi_attachment.URL_
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.CONTENT_ID_
     *
     * @return the value of act_hi_attachment.CONTENT_ID_
     *
     * @mbggenerated
     */
    public String getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.CONTENT_ID_
     *
     * @param contentId the value for act_hi_attachment.CONTENT_ID_
     *
     * @mbggenerated
     */
    public void setContentId(String contentId) {
        this.contentId = contentId == null ? null : contentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_attachment.TIME_
     *
     * @return the value of act_hi_attachment.TIME_
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_attachment.TIME_
     *
     * @param time the value for act_hi_attachment.TIME_
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}