package com.ltkj.app.common.model;

import java.util.Date;

public class HiProcinst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.ID_
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.PROC_INST_ID_
     *
     * @mbggenerated
     */
    private String procInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.BUSINESS_KEY_
     *
     * @mbggenerated
     */
    private String businessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.PROC_DEF_ID_
     *
     * @mbggenerated
     */
    private String procDefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.START_TIME_
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.END_TIME_
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.DURATION_
     *
     * @mbggenerated
     */
    private Long duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.START_USER_ID_
     *
     * @mbggenerated
     */
    private String startUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.START_ACT_ID_
     *
     * @mbggenerated
     */
    private String startActId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.END_ACT_ID_
     *
     * @mbggenerated
     */
    private String endActId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbggenerated
     */
    private String superProcessInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.DELETE_REASON_
     *
     * @mbggenerated
     */
    private String deleteReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.TENANT_ID_
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_procinst.NAME_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.ID_
     *
     * @return the value of act_hi_procinst.ID_
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.ID_
     *
     * @param id the value for act_hi_procinst.ID_
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.PROC_INST_ID_
     *
     * @return the value of act_hi_procinst.PROC_INST_ID_
     *
     * @mbggenerated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_procinst.PROC_INST_ID_
     *
     * @mbggenerated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.BUSINESS_KEY_
     *
     * @return the value of act_hi_procinst.BUSINESS_KEY_
     *
     * @mbggenerated
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.BUSINESS_KEY_
     *
     * @param businessKey the value for act_hi_procinst.BUSINESS_KEY_
     *
     * @mbggenerated
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey == null ? null : businessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.PROC_DEF_ID_
     *
     * @return the value of act_hi_procinst.PROC_DEF_ID_
     *
     * @mbggenerated
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.PROC_DEF_ID_
     *
     * @param procDefId the value for act_hi_procinst.PROC_DEF_ID_
     *
     * @mbggenerated
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.START_TIME_
     *
     * @return the value of act_hi_procinst.START_TIME_
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.START_TIME_
     *
     * @param startTime the value for act_hi_procinst.START_TIME_
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.END_TIME_
     *
     * @return the value of act_hi_procinst.END_TIME_
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.END_TIME_
     *
     * @param endTime the value for act_hi_procinst.END_TIME_
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.DURATION_
     *
     * @return the value of act_hi_procinst.DURATION_
     *
     * @mbggenerated
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.DURATION_
     *
     * @param duration the value for act_hi_procinst.DURATION_
     *
     * @mbggenerated
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.START_USER_ID_
     *
     * @return the value of act_hi_procinst.START_USER_ID_
     *
     * @mbggenerated
     */
    public String getStartUserId() {
        return startUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.START_USER_ID_
     *
     * @param startUserId the value for act_hi_procinst.START_USER_ID_
     *
     * @mbggenerated
     */
    public void setStartUserId(String startUserId) {
        this.startUserId = startUserId == null ? null : startUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.START_ACT_ID_
     *
     * @return the value of act_hi_procinst.START_ACT_ID_
     *
     * @mbggenerated
     */
    public String getStartActId() {
        return startActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.START_ACT_ID_
     *
     * @param startActId the value for act_hi_procinst.START_ACT_ID_
     *
     * @mbggenerated
     */
    public void setStartActId(String startActId) {
        this.startActId = startActId == null ? null : startActId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.END_ACT_ID_
     *
     * @return the value of act_hi_procinst.END_ACT_ID_
     *
     * @mbggenerated
     */
    public String getEndActId() {
        return endActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.END_ACT_ID_
     *
     * @param endActId the value for act_hi_procinst.END_ACT_ID_
     *
     * @mbggenerated
     */
    public void setEndActId(String endActId) {
        this.endActId = endActId == null ? null : endActId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @return the value of act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbggenerated
     */
    public String getSuperProcessInstanceId() {
        return superProcessInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @param superProcessInstanceId the value for act_hi_procinst.SUPER_PROCESS_INSTANCE_ID_
     *
     * @mbggenerated
     */
    public void setSuperProcessInstanceId(String superProcessInstanceId) {
        this.superProcessInstanceId = superProcessInstanceId == null ? null : superProcessInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.DELETE_REASON_
     *
     * @return the value of act_hi_procinst.DELETE_REASON_
     *
     * @mbggenerated
     */
    public String getDeleteReason() {
        return deleteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.DELETE_REASON_
     *
     * @param deleteReason the value for act_hi_procinst.DELETE_REASON_
     *
     * @mbggenerated
     */
    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason == null ? null : deleteReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.TENANT_ID_
     *
     * @return the value of act_hi_procinst.TENANT_ID_
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.TENANT_ID_
     *
     * @param tenantId the value for act_hi_procinst.TENANT_ID_
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_procinst.NAME_
     *
     * @return the value of act_hi_procinst.NAME_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_procinst.NAME_
     *
     * @param name the value for act_hi_procinst.NAME_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}