package com.ltkj.app.common.model;

import java.util.Date;

public class Mast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Company_Id
     *
     * @mbggenerated
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Catgory_Id1
     *
     * @mbggenerated
     */
    private String catgoryId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Catgory_Id2
     *
     * @mbggenerated
     */
    private String catgoryId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Catgory_Id3
     *
     * @mbggenerated
     */
    private String catgoryId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Catgory_Id4
     *
     * @mbggenerated
     */
    private String catgoryId4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Key_Cd
     *
     * @mbggenerated
     */
    private String keyCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Key_Value
     *
     * @mbggenerated
     */
    private String keyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Disp_Order
     *
     * @mbggenerated
     */
    private Integer dispOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Comment1
     *
     * @mbggenerated
     */
    private String comment1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Comment2
     *
     * @mbggenerated
     */
    private String comment2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Is_Active
     *
     * @mbggenerated
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.Is_Display
     *
     * @mbggenerated
     */
    private String isDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.CREATE_DT
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.CREATE_OP
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.CREATE_PG
     *
     * @mbggenerated
     */
    private String createPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.UPDATE_DT
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.UPDATE_OP
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_master.UPDATE_PG
     *
     * @mbggenerated
     */
    private String updatePg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.uuid
     *
     * @return the value of t_master.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.uuid
     *
     * @param uuid the value for t_master.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Company_Id
     *
     * @return the value of t_master.Company_Id
     *
     * @mbggenerated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Company_Id
     *
     * @param companyId the value for t_master.Company_Id
     *
     * @mbggenerated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Catgory_Id1
     *
     * @return the value of t_master.Catgory_Id1
     *
     * @mbggenerated
     */
    public String getCatgoryId1() {
        return catgoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Catgory_Id1
     *
     * @param catgoryId1 the value for t_master.Catgory_Id1
     *
     * @mbggenerated
     */
    public void setCatgoryId1(String catgoryId1) {
        this.catgoryId1 = catgoryId1 == null ? null : catgoryId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Catgory_Id2
     *
     * @return the value of t_master.Catgory_Id2
     *
     * @mbggenerated
     */
    public String getCatgoryId2() {
        return catgoryId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Catgory_Id2
     *
     * @param catgoryId2 the value for t_master.Catgory_Id2
     *
     * @mbggenerated
     */
    public void setCatgoryId2(String catgoryId2) {
        this.catgoryId2 = catgoryId2 == null ? null : catgoryId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Catgory_Id3
     *
     * @return the value of t_master.Catgory_Id3
     *
     * @mbggenerated
     */
    public String getCatgoryId3() {
        return catgoryId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Catgory_Id3
     *
     * @param catgoryId3 the value for t_master.Catgory_Id3
     *
     * @mbggenerated
     */
    public void setCatgoryId3(String catgoryId3) {
        this.catgoryId3 = catgoryId3 == null ? null : catgoryId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Catgory_Id4
     *
     * @return the value of t_master.Catgory_Id4
     *
     * @mbggenerated
     */
    public String getCatgoryId4() {
        return catgoryId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Catgory_Id4
     *
     * @param catgoryId4 the value for t_master.Catgory_Id4
     *
     * @mbggenerated
     */
    public void setCatgoryId4(String catgoryId4) {
        this.catgoryId4 = catgoryId4 == null ? null : catgoryId4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Category
     *
     * @return the value of t_master.Category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Category
     *
     * @param category the value for t_master.Category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Key_Cd
     *
     * @return the value of t_master.Key_Cd
     *
     * @mbggenerated
     */
    public String getKeyCd() {
        return keyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Key_Cd
     *
     * @param keyCd the value for t_master.Key_Cd
     *
     * @mbggenerated
     */
    public void setKeyCd(String keyCd) {
        this.keyCd = keyCd == null ? null : keyCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Key_Value
     *
     * @return the value of t_master.Key_Value
     *
     * @mbggenerated
     */
    public String getKeyValue() {
        return keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Key_Value
     *
     * @param keyValue the value for t_master.Key_Value
     *
     * @mbggenerated
     */
    public void setKeyValue(String keyValue) {
        this.keyValue = keyValue == null ? null : keyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Disp_Order
     *
     * @return the value of t_master.Disp_Order
     *
     * @mbggenerated
     */
    public Integer getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Disp_Order
     *
     * @param dispOrder the value for t_master.Disp_Order
     *
     * @mbggenerated
     */
    public void setDispOrder(Integer dispOrder) {
        this.dispOrder = dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Description
     *
     * @return the value of t_master.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Description
     *
     * @param description the value for t_master.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Comment1
     *
     * @return the value of t_master.Comment1
     *
     * @mbggenerated
     */
    public String getComment1() {
        return comment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Comment1
     *
     * @param comment1 the value for t_master.Comment1
     *
     * @mbggenerated
     */
    public void setComment1(String comment1) {
        this.comment1 = comment1 == null ? null : comment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Comment2
     *
     * @return the value of t_master.Comment2
     *
     * @mbggenerated
     */
    public String getComment2() {
        return comment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Comment2
     *
     * @param comment2 the value for t_master.Comment2
     *
     * @mbggenerated
     */
    public void setComment2(String comment2) {
        this.comment2 = comment2 == null ? null : comment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Is_Active
     *
     * @return the value of t_master.Is_Active
     *
     * @mbggenerated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Is_Active
     *
     * @param isActive the value for t_master.Is_Active
     *
     * @mbggenerated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.Is_Display
     *
     * @return the value of t_master.Is_Display
     *
     * @mbggenerated
     */
    public String getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.Is_Display
     *
     * @param isDisplay the value for t_master.Is_Display
     *
     * @mbggenerated
     */
    public void setIsDisplay(String isDisplay) {
        this.isDisplay = isDisplay == null ? null : isDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.CREATE_DT
     *
     * @return the value of t_master.CREATE_DT
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.CREATE_DT
     *
     * @param createDt the value for t_master.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.CREATE_OP
     *
     * @return the value of t_master.CREATE_OP
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.CREATE_OP
     *
     * @param createOp the value for t_master.CREATE_OP
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.CREATE_PG
     *
     * @return the value of t_master.CREATE_PG
     *
     * @mbggenerated
     */
    public String getCreatePg() {
        return createPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.CREATE_PG
     *
     * @param createPg the value for t_master.CREATE_PG
     *
     * @mbggenerated
     */
    public void setCreatePg(String createPg) {
        this.createPg = createPg == null ? null : createPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.UPDATE_DT
     *
     * @return the value of t_master.UPDATE_DT
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.UPDATE_DT
     *
     * @param updateDt the value for t_master.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.UPDATE_OP
     *
     * @return the value of t_master.UPDATE_OP
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.UPDATE_OP
     *
     * @param updateOp the value for t_master.UPDATE_OP
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_master.UPDATE_PG
     *
     * @return the value of t_master.UPDATE_PG
     *
     * @mbggenerated
     */
    public String getUpdatePg() {
        return updatePg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_master.UPDATE_PG
     *
     * @param updatePg the value for t_master.UPDATE_PG
     *
     * @mbggenerated
     */
    public void setUpdatePg(String updatePg) {
        this.updatePg = updatePg == null ? null : updatePg.trim();
    }
}