package com.ltkj.app.common.model;

import java.math.BigDecimal;

public class OrderDetail extends OrderDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order_detail.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order_detail.spec
     *
     * @mbggenerated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order_detail.buying_price
     *
     * @mbggenerated
     */
    private BigDecimal buyingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order_detail.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order_detail.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_order_detail.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_order_detail.goods_name
     *
     * @return the value of s_order_detail.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_order_detail.goods_name
     *
     * @param goodsName the value for s_order_detail.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_order_detail.spec
     *
     * @return the value of s_order_detail.spec
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_order_detail.spec
     *
     * @param spec the value for s_order_detail.spec
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_order_detail.buying_price
     *
     * @return the value of s_order_detail.buying_price
     *
     * @mbggenerated
     */
    public BigDecimal getBuyingPrice() {
        return buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_order_detail.buying_price
     *
     * @param buyingPrice the value for s_order_detail.buying_price
     *
     * @mbggenerated
     */
    public void setBuyingPrice(BigDecimal buyingPrice) {
        this.buyingPrice = buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_order_detail.price
     *
     * @return the value of s_order_detail.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_order_detail.price
     *
     * @param price the value for s_order_detail.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_order_detail.quantity
     *
     * @return the value of s_order_detail.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_order_detail.quantity
     *
     * @param quantity the value for s_order_detail.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_order_detail.order_num
     *
     * @return the value of s_order_detail.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_order_detail.order_num
     *
     * @param orderNum the value for s_order_detail.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}