package com.ltkj.app.common.model;

import java.util.Date;

public class Organizational {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_fId
     *
     * @mbggenerated
     */
    private String orgFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_fName
     *
     * @mbggenerated
     */
    private String orgFname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_level
     *
     * @mbggenerated
     */
    private Integer orgLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.org_type
     *
     * @mbggenerated
     */
    private String orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.is_remove
     *
     * @mbggenerated
     */
    private String isRemove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.id
     *
     * @return the value of sys_org.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.id
     *
     * @param id the value for sys_org.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_name
     *
     * @return the value of sys_org.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_name
     *
     * @param orgName the value for sys_org.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_fId
     *
     * @return the value of sys_org.org_fId
     *
     * @mbggenerated
     */
    public String getOrgFid() {
        return orgFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_fId
     *
     * @param orgFid the value for sys_org.org_fId
     *
     * @mbggenerated
     */
    public void setOrgFid(String orgFid) {
        this.orgFid = orgFid == null ? null : orgFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_fName
     *
     * @return the value of sys_org.org_fName
     *
     * @mbggenerated
     */
    public String getOrgFname() {
        return orgFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_fName
     *
     * @param orgFname the value for sys_org.org_fName
     *
     * @mbggenerated
     */
    public void setOrgFname(String orgFname) {
        this.orgFname = orgFname == null ? null : orgFname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_level
     *
     * @return the value of sys_org.org_level
     *
     * @mbggenerated
     */
    public Integer getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_level
     *
     * @param orgLevel the value for sys_org.org_level
     *
     * @mbggenerated
     */
    public void setOrgLevel(Integer orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.org_type
     *
     * @return the value of sys_org.org_type
     *
     * @mbggenerated
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.org_type
     *
     * @param orgType the value for sys_org.org_type
     *
     * @mbggenerated
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType == null ? null : orgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.parent_id
     *
     * @return the value of sys_org.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.parent_id
     *
     * @param parentId the value for sys_org.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.comments
     *
     * @return the value of sys_org.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.comments
     *
     * @param comments the value for sys_org.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.is_remove
     *
     * @return the value of sys_org.is_remove
     *
     * @mbggenerated
     */
    public String getIsRemove() {
        return isRemove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.is_remove
     *
     * @param isRemove the value for sys_org.is_remove
     *
     * @mbggenerated
     */
    public void setIsRemove(String isRemove) {
        this.isRemove = isRemove == null ? null : isRemove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.create_time
     *
     * @return the value of sys_org.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.create_time
     *
     * @param createTime the value for sys_org.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.create_user
     *
     * @return the value of sys_org.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.create_user
     *
     * @param createUser the value for sys_org.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.update_time
     *
     * @return the value of sys_org.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.update_time
     *
     * @param updateTime the value for sys_org.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.update_user
     *
     * @return the value of sys_org.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.update_user
     *
     * @param updateUser the value for sys_org.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}