package com.ltkj.app.common.model;

import java.util.Date;

public class ReDeployment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.ID_
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.NAME_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.CATEGORY_
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.TENANT_ID_
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.DEPLOY_TIME_
     *
     * @mbggenerated
     */
    private Date deployTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.ID_
     *
     * @return the value of act_re_deployment.ID_
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.ID_
     *
     * @param id the value for act_re_deployment.ID_
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.NAME_
     *
     * @return the value of act_re_deployment.NAME_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.NAME_
     *
     * @param name the value for act_re_deployment.NAME_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.CATEGORY_
     *
     * @return the value of act_re_deployment.CATEGORY_
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.CATEGORY_
     *
     * @param category the value for act_re_deployment.CATEGORY_
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.TENANT_ID_
     *
     * @return the value of act_re_deployment.TENANT_ID_
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.TENANT_ID_
     *
     * @param tenantId the value for act_re_deployment.TENANT_ID_
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.DEPLOY_TIME_
     *
     * @return the value of act_re_deployment.DEPLOY_TIME_
     *
     * @mbggenerated
     */
    public Date getDeployTime() {
        return deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.DEPLOY_TIME_
     *
     * @param deployTime the value for act_re_deployment.DEPLOY_TIME_
     *
     * @mbggenerated
     */
    public void setDeployTime(Date deployTime) {
        this.deployTime = deployTime;
    }
}