package com.ltkj.app.common.model;

import java.util.Date;

public class ReModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.ID_
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.REV_
     *
     * @mbggenerated
     */
    private Integer rev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.NAME_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.KEY_
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.CATEGORY_
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.CREATE_TIME_
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.LAST_UPDATE_TIME_
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.VERSION_
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.META_INFO_
     *
     * @mbggenerated
     */
    private String metaInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    private String deploymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @mbggenerated
     */
    private String editorSourceValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @mbggenerated
     */
    private String editorSourceExtraValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.TENANT_ID_
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.ID_
     *
     * @return the value of act_re_model.ID_
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.ID_
     *
     * @param id the value for act_re_model.ID_
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.REV_
     *
     * @return the value of act_re_model.REV_
     *
     * @mbggenerated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.REV_
     *
     * @param rev the value for act_re_model.REV_
     *
     * @mbggenerated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.NAME_
     *
     * @return the value of act_re_model.NAME_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.NAME_
     *
     * @param name the value for act_re_model.NAME_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.KEY_
     *
     * @return the value of act_re_model.KEY_
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.KEY_
     *
     * @param key the value for act_re_model.KEY_
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.CATEGORY_
     *
     * @return the value of act_re_model.CATEGORY_
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.CATEGORY_
     *
     * @param category the value for act_re_model.CATEGORY_
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.CREATE_TIME_
     *
     * @return the value of act_re_model.CREATE_TIME_
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.CREATE_TIME_
     *
     * @param createTime the value for act_re_model.CREATE_TIME_
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.LAST_UPDATE_TIME_
     *
     * @return the value of act_re_model.LAST_UPDATE_TIME_
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.LAST_UPDATE_TIME_
     *
     * @param lastUpdateTime the value for act_re_model.LAST_UPDATE_TIME_
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.VERSION_
     *
     * @return the value of act_re_model.VERSION_
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.VERSION_
     *
     * @param version the value for act_re_model.VERSION_
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.META_INFO_
     *
     * @return the value of act_re_model.META_INFO_
     *
     * @mbggenerated
     */
    public String getMetaInfo() {
        return metaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.META_INFO_
     *
     * @param metaInfo the value for act_re_model.META_INFO_
     *
     * @mbggenerated
     */
    public void setMetaInfo(String metaInfo) {
        this.metaInfo = metaInfo == null ? null : metaInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.DEPLOYMENT_ID_
     *
     * @return the value of act_re_model.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_re_model.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @return the value of act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @mbggenerated
     */
    public String getEditorSourceValueId() {
        return editorSourceValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @param editorSourceValueId the value for act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @mbggenerated
     */
    public void setEditorSourceValueId(String editorSourceValueId) {
        this.editorSourceValueId = editorSourceValueId == null ? null : editorSourceValueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @return the value of act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @mbggenerated
     */
    public String getEditorSourceExtraValueId() {
        return editorSourceExtraValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @param editorSourceExtraValueId the value for act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @mbggenerated
     */
    public void setEditorSourceExtraValueId(String editorSourceExtraValueId) {
        this.editorSourceExtraValueId = editorSourceExtraValueId == null ? null : editorSourceExtraValueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.TENANT_ID_
     *
     * @return the value of act_re_model.TENANT_ID_
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.TENANT_ID_
     *
     * @param tenantId the value for act_re_model.TENANT_ID_
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}