package com.ltkj.app.common.model;

public class ReProcdef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.ID_
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.REV_
     *
     * @mbggenerated
     */
    private Integer rev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.CATEGORY_
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.NAME_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.KEY_
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.VERSION_
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    private String deploymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.RESOURCE_NAME_
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbggenerated
     */
    private String dgrmResourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DESCRIPTION_
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbggenerated
     */
    private Byte hasStartFormKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @mbggenerated
     */
    private Byte hasGraphicalNotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @mbggenerated
     */
    private Integer suspensionState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.TENANT_ID_
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.ID_
     *
     * @return the value of act_re_procdef.ID_
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.ID_
     *
     * @param id the value for act_re_procdef.ID_
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.REV_
     *
     * @return the value of act_re_procdef.REV_
     *
     * @mbggenerated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.REV_
     *
     * @param rev the value for act_re_procdef.REV_
     *
     * @mbggenerated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.CATEGORY_
     *
     * @return the value of act_re_procdef.CATEGORY_
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.CATEGORY_
     *
     * @param category the value for act_re_procdef.CATEGORY_
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.NAME_
     *
     * @return the value of act_re_procdef.NAME_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.NAME_
     *
     * @param name the value for act_re_procdef.NAME_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.KEY_
     *
     * @return the value of act_re_procdef.KEY_
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.KEY_
     *
     * @param key the value for act_re_procdef.KEY_
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.VERSION_
     *
     * @return the value of act_re_procdef.VERSION_
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.VERSION_
     *
     * @param version the value for act_re_procdef.VERSION_
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @return the value of act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbggenerated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.RESOURCE_NAME_
     *
     * @return the value of act_re_procdef.RESOURCE_NAME_
     *
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.RESOURCE_NAME_
     *
     * @param resourceName the value for act_re_procdef.RESOURCE_NAME_
     *
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @return the value of act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbggenerated
     */
    public String getDgrmResourceName() {
        return dgrmResourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @param dgrmResourceName the value for act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbggenerated
     */
    public void setDgrmResourceName(String dgrmResourceName) {
        this.dgrmResourceName = dgrmResourceName == null ? null : dgrmResourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DESCRIPTION_
     *
     * @return the value of act_re_procdef.DESCRIPTION_
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DESCRIPTION_
     *
     * @param description the value for act_re_procdef.DESCRIPTION_
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @return the value of act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbggenerated
     */
    public Byte getHasStartFormKey() {
        return hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @param hasStartFormKey the value for act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbggenerated
     */
    public void setHasStartFormKey(Byte hasStartFormKey) {
        this.hasStartFormKey = hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @return the value of act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @mbggenerated
     */
    public Byte getHasGraphicalNotation() {
        return hasGraphicalNotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @param hasGraphicalNotation the value for act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @mbggenerated
     */
    public void setHasGraphicalNotation(Byte hasGraphicalNotation) {
        this.hasGraphicalNotation = hasGraphicalNotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @return the value of act_re_procdef.SUSPENSION_STATE_
     *
     * @mbggenerated
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @param suspensionState the value for act_re_procdef.SUSPENSION_STATE_
     *
     * @mbggenerated
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.TENANT_ID_
     *
     * @return the value of act_re_procdef.TENANT_ID_
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.TENANT_ID_
     *
     * @param tenantId the value for act_re_procdef.TENANT_ID_
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}