package com.ltkj.app.common.model;

import java.util.Date;

public class Resources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_name
     *
     * @mbggenerated
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_fid
     *
     * @mbggenerated
     */
    private String resFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_fname
     *
     * @mbggenerated
     */
    private String resFname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_type
     *
     * @mbggenerated
     */
    private String resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_url
     *
     * @mbggenerated
     */
    private String resUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_icon
     *
     * @mbggenerated
     */
    private String resIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_level
     *
     * @mbggenerated
     */
    private Integer resLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.is_hidden
     *
     * @mbggenerated
     */
    private String isHidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.is_remove
     *
     * @mbggenerated
     */
    private String isRemove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.id
     *
     * @return the value of sys_resources.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.id
     *
     * @param id the value for sys_resources.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_name
     *
     * @return the value of sys_resources.res_name
     *
     * @mbggenerated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_name
     *
     * @param resName the value for sys_resources.res_name
     *
     * @mbggenerated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.parent_id
     *
     * @return the value of sys_resources.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.parent_id
     *
     * @param parentId the value for sys_resources.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_fid
     *
     * @return the value of sys_resources.res_fid
     *
     * @mbggenerated
     */
    public String getResFid() {
        return resFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_fid
     *
     * @param resFid the value for sys_resources.res_fid
     *
     * @mbggenerated
     */
    public void setResFid(String resFid) {
        this.resFid = resFid == null ? null : resFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_fname
     *
     * @return the value of sys_resources.res_fname
     *
     * @mbggenerated
     */
    public String getResFname() {
        return resFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_fname
     *
     * @param resFname the value for sys_resources.res_fname
     *
     * @mbggenerated
     */
    public void setResFname(String resFname) {
        this.resFname = resFname == null ? null : resFname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_type
     *
     * @return the value of sys_resources.res_type
     *
     * @mbggenerated
     */
    public String getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_type
     *
     * @param resType the value for sys_resources.res_type
     *
     * @mbggenerated
     */
    public void setResType(String resType) {
        this.resType = resType == null ? null : resType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_url
     *
     * @return the value of sys_resources.res_url
     *
     * @mbggenerated
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_url
     *
     * @param resUrl the value for sys_resources.res_url
     *
     * @mbggenerated
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl == null ? null : resUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_icon
     *
     * @return the value of sys_resources.res_icon
     *
     * @mbggenerated
     */
    public String getResIcon() {
        return resIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_icon
     *
     * @param resIcon the value for sys_resources.res_icon
     *
     * @mbggenerated
     */
    public void setResIcon(String resIcon) {
        this.resIcon = resIcon == null ? null : resIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_level
     *
     * @return the value of sys_resources.res_level
     *
     * @mbggenerated
     */
    public Integer getResLevel() {
        return resLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_level
     *
     * @param resLevel the value for sys_resources.res_level
     *
     * @mbggenerated
     */
    public void setResLevel(Integer resLevel) {
        this.resLevel = resLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.is_hidden
     *
     * @return the value of sys_resources.is_hidden
     *
     * @mbggenerated
     */
    public String getIsHidden() {
        return isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.is_hidden
     *
     * @param isHidden the value for sys_resources.is_hidden
     *
     * @mbggenerated
     */
    public void setIsHidden(String isHidden) {
        this.isHidden = isHidden == null ? null : isHidden.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.is_remove
     *
     * @return the value of sys_resources.is_remove
     *
     * @mbggenerated
     */
    public String getIsRemove() {
        return isRemove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.is_remove
     *
     * @param isRemove the value for sys_resources.is_remove
     *
     * @mbggenerated
     */
    public void setIsRemove(String isRemove) {
        this.isRemove = isRemove == null ? null : isRemove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.comments
     *
     * @return the value of sys_resources.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.comments
     *
     * @param comments the value for sys_resources.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_time
     *
     * @return the value of sys_resources.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_time
     *
     * @param createTime the value for sys_resources.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_user
     *
     * @return the value of sys_resources.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_user
     *
     * @param createUser the value for sys_resources.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_time
     *
     * @return the value of sys_resources.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_time
     *
     * @param updateTime the value for sys_resources.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_user
     *
     * @return the value of sys_resources.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_user
     *
     * @param updateUser the value for sys_resources.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}