package com.ltkj.app.common.model;

public class Sequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sequence.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sequence.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sequence.current_value
     *
     * @mbggenerated
     */
    private String currentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sequence._increment
     *
     * @mbggenerated
     */
    private Integer increment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sequence.pre
     *
     * @mbggenerated
     */
    private String pre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sequence._format
     *
     * @mbggenerated
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sequence.org_id
     *
     * @mbggenerated
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sequence.id
     *
     * @return the value of tb_sequence.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sequence.id
     *
     * @param id the value for tb_sequence.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sequence.name
     *
     * @return the value of tb_sequence.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sequence.name
     *
     * @param name the value for tb_sequence.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sequence.current_value
     *
     * @return the value of tb_sequence.current_value
     *
     * @mbggenerated
     */
    public String getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sequence.current_value
     *
     * @param currentValue the value for tb_sequence.current_value
     *
     * @mbggenerated
     */
    public void setCurrentValue(String currentValue) {
        this.currentValue = currentValue == null ? null : currentValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sequence._increment
     *
     * @return the value of tb_sequence._increment
     *
     * @mbggenerated
     */
    public Integer getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sequence._increment
     *
     * @param increment the value for tb_sequence._increment
     *
     * @mbggenerated
     */
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sequence.pre
     *
     * @return the value of tb_sequence.pre
     *
     * @mbggenerated
     */
    public String getPre() {
        return pre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sequence.pre
     *
     * @param pre the value for tb_sequence.pre
     *
     * @mbggenerated
     */
    public void setPre(String pre) {
        this.pre = pre == null ? null : pre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sequence._format
     *
     * @return the value of tb_sequence._format
     *
     * @mbggenerated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sequence._format
     *
     * @param format the value for tb_sequence._format
     *
     * @mbggenerated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sequence.org_id
     *
     * @return the value of tb_sequence.org_id
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sequence.org_id
     *
     * @param orgId the value for tb_sequence.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }
}