package com.ltkj.app.common.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Sfood implements Serializable{
   
	private static final long serialVersionUID = -1416564934872847363L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.food_name
     *
     * @mbggenerated
     */
    private String foodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.food_code
     *
     * @mbggenerated
     */
    private String foodCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.food_type
     *
     * @mbggenerated
     */
    private String foodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.food_price
     *
     * @mbggenerated
     */
    private BigDecimal foodPrice;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.food_number
     *
     * @mbggenerated
     */
    private Integer foodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.food_origin
     *
     * @mbggenerated
     */
    private String foodOrigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.food_exp
     *
     * @mbggenerated
     */
    private String foodExp;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.foodPic
     *
     * @mbggenerated
     */
    private String foodPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.Is_Active
     *
     * @mbggenerated
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.CREATE_DT
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.CREATE_OP
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.CREATE_PG
     *
     * @mbggenerated
     */
    private String createPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.UPDATE_DT
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.UPDATE_OP
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_sfood.UPDATE_PG
     *
     * @mbggenerated
     */
    private String updatePg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.uuid
     *
     * @return the value of w_sfood.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.uuid
     *
     * @param uuid the value for w_sfood.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_name
     *
     * @return the value of w_sfood.food_name
     *
     * @mbggenerated
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_name
     *
     * @param foodName the value for w_sfood.food_name
     *
     * @mbggenerated
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_code
     *
     * @return the value of w_sfood.food_code
     *
     * @mbggenerated
     */
    public String getFoodCode() {
        return foodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_code
     *
     * @param foodCode the value for w_sfood.food_code
     *
     * @mbggenerated
     */
    public void setFoodCode(String foodCode) {
        this.foodCode = foodCode == null ? null : foodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_type
     *
     * @return the value of w_sfood.food_type
     *
     * @mbggenerated
     */
    public String getFoodType() {
        return foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_type
     *
     * @param foodType the value for w_sfood.food_type
     *
     * @mbggenerated
     */
    public void setFoodType(String foodType) {
        this.foodType = foodType == null ? null : foodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_price
     *
     * @return the value of w_sfood.food_price
     *
     * @mbggenerated
     */
    public BigDecimal getFoodPrice() {
        return foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_price
     *
     * @param foodPrice the value for w_sfood.food_price
     *
     * @mbggenerated
     */
    public void setFoodPrice(BigDecimal foodPrice) {
        this.foodPrice = foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_origin
     *
     * @return the value of w_sfood.food_origin
     *
     * @mbggenerated
     */
    public String getFoodOrigin() {
        return foodOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_origin
     *
     * @param foodOrigin the value for w_sfood.food_origin
     *
     * @mbggenerated
     */
    public void setFoodOrigin(String foodOrigin) {
        this.foodOrigin = foodOrigin == null ? null : foodOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_exp
     *
     * @return the value of w_sfood.food_exp
     *
     * @mbggenerated
     */
    public String getFoodExp() {
        return foodExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_exp
     *
     * @param foodExp the value for w_sfood.food_exp
     *
     * @mbggenerated
     */
    public void setFoodExp(String foodExp) {
        this.foodExp = foodExp == null ? null : foodExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.Is_Active
     *
     * @return the value of w_sfood.Is_Active
     *
     * @mbggenerated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.Is_Active
     *
     * @param isActive the value for w_sfood.Is_Active
     *
     * @mbggenerated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.CREATE_DT
     *
     * @return the value of w_sfood.CREATE_DT
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.CREATE_DT
     *
     * @param createDt the value for w_sfood.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.CREATE_OP
     *
     * @return the value of w_sfood.CREATE_OP
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.CREATE_OP
     *
     * @param createOp the value for w_sfood.CREATE_OP
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.CREATE_PG
     *
     * @return the value of w_sfood.CREATE_PG
     *
     * @mbggenerated
     */
    public String getCreatePg() {
        return createPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.CREATE_PG
     *
     * @param createPg the value for w_sfood.CREATE_PG
     *
     * @mbggenerated
     */
    public void setCreatePg(String createPg) {
        this.createPg = createPg == null ? null : createPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.UPDATE_DT
     *
     * @return the value of w_sfood.UPDATE_DT
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.UPDATE_DT
     *
     * @param updateDt the value for w_sfood.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.UPDATE_OP
     *
     * @return the value of w_sfood.UPDATE_OP
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.UPDATE_OP
     *
     * @param updateOp the value for w_sfood.UPDATE_OP
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.UPDATE_PG
     *
     * @return the value of w_sfood.UPDATE_PG
     *
     * @mbggenerated
     */
    public String getUpdatePg() {
        return updatePg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.UPDATE_PG
     *
     * @param updatePg the value for w_sfood.UPDATE_PG
     *
     * @mbggenerated
     */
    public void setUpdatePg(String updatePg) {
        this.updatePg = updatePg == null ? null : updatePg.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_number
     *
     * @return the value of w_sfood.food_number
     *
     * @mbggenerated
     */
	public Integer getFoodNumber() {
		return foodNumber;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_number
     *
     * @param updatePg the value for w_sfood.food_number
     *
     * @mbggenerated
     */
	public void setFoodNumber(Integer foodNumber) {
		this.foodNumber = foodNumber;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_sfood.food_pic
     *
     * @return the value of w_sfood.food_pic
     *
     * @mbggenerated
     */

	public String getFoodPic() {
		return foodPic;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_sfood.food_pic
     *
     * @param updatePg the value for w_sfood.food_pic
     *
     * @mbggenerated
     */
	public void setFoodPic(String foodPic) {
		this.foodPic = foodPic;
	}
}