package com.ltkj.app.common.model;

public class Students {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.stu_name
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.stu_major
     *
     * @mbggenerated
     */
    private String stuMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.cou_name
     *
     * @mbggenerated
     */
    private String couName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.cou_type
     *
     * @mbggenerated
     */
    private String couType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.stu_gra
     *
     * @mbggenerated
     */
    private Integer stuGra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.gra_max
     *
     * @mbggenerated
     */
    private Integer graMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.gra_min
     *
     * @mbggenerated
     */
    private Integer graMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.stu_sex
     *
     * @mbggenerated
     */
    private String stuSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_students.instruction
     *
     * @mbggenerated
     */
    private String instruction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.stu_id
     *
     * @return the value of s_students.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.stu_id
     *
     * @param stuId the value for s_students.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.stu_name
     *
     * @return the value of s_students.stu_name
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.stu_name
     *
     * @param stuName the value for s_students.stu_name
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.stu_major
     *
     * @return the value of s_students.stu_major
     *
     * @mbggenerated
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.stu_major
     *
     * @param stuMajor the value for s_students.stu_major
     *
     * @mbggenerated
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor == null ? null : stuMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.cou_name
     *
     * @return the value of s_students.cou_name
     *
     * @mbggenerated
     */
    public String getCouName() {
        return couName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.cou_name
     *
     * @param couName the value for s_students.cou_name
     *
     * @mbggenerated
     */
    public void setCouName(String couName) {
        this.couName = couName == null ? null : couName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.cou_type
     *
     * @return the value of s_students.cou_type
     *
     * @mbggenerated
     */
    public String getCouType() {
        return couType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.cou_type
     *
     * @param couType the value for s_students.cou_type
     *
     * @mbggenerated
     */
    public void setCouType(String couType) {
        this.couType = couType == null ? null : couType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.stu_gra
     *
     * @return the value of s_students.stu_gra
     *
     * @mbggenerated
     */
    public Integer getStuGra() {
        return stuGra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.stu_gra
     *
     * @param stuGra the value for s_students.stu_gra
     *
     * @mbggenerated
     */
    public void setStuGra(Integer stuGra) {
        this.stuGra = stuGra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.gra_max
     *
     * @return the value of s_students.gra_max
     *
     * @mbggenerated
     */
    public Integer getGraMax() {
        return graMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.gra_max
     *
     * @param graMax the value for s_students.gra_max
     *
     * @mbggenerated
     */
    public void setGraMax(Integer graMax) {
        this.graMax = graMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.gra_min
     *
     * @return the value of s_students.gra_min
     *
     * @mbggenerated
     */
    public Integer getGraMin() {
        return graMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.gra_min
     *
     * @param graMin the value for s_students.gra_min
     *
     * @mbggenerated
     */
    public void setGraMin(Integer graMin) {
        this.graMin = graMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.stu_sex
     *
     * @return the value of s_students.stu_sex
     *
     * @mbggenerated
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.stu_sex
     *
     * @param stuSex the value for s_students.stu_sex
     *
     * @mbggenerated
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex == null ? null : stuSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_students.instruction
     *
     * @return the value of s_students.instruction
     *
     * @mbggenerated
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_students.instruction
     *
     * @param instruction the value for s_students.instruction
     *
     * @mbggenerated
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }
}