package com.ltkj.app.common.model;

import java.util.Date;

public class Tuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_password
     *
     * @mbggenerated
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_sex
     *
     * @mbggenerated
     */
    private String uSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_age
     *
     * @mbggenerated
     */
    private String uAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_class
     *
     * @mbggenerated
     */
    private Integer uClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CREATE_DT
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CREATE_OP
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CREATE_PG
     *
     * @mbggenerated
     */
    private String createPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UPDATE_DT
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UPDATE_OP
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UPDATE_PG
     *
     * @mbggenerated
     */
    private String updatePg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uuid
     *
     * @return the value of t_user.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uuid
     *
     * @param uuid the value for t_user.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_name
     *
     * @return the value of t_user.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_name
     *
     * @param uName the value for t_user.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_password
     *
     * @return the value of t_user.u_password
     *
     * @mbggenerated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_password
     *
     * @param uPassword the value for t_user.u_password
     *
     * @mbggenerated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_sex
     *
     * @return the value of t_user.u_sex
     *
     * @mbggenerated
     */
    public String getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_sex
     *
     * @param uSex the value for t_user.u_sex
     *
     * @mbggenerated
     */
    public void setuSex(String uSex) {
        this.uSex = uSex == null ? null : uSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_age
     *
     * @return the value of t_user.u_age
     *
     * @mbggenerated
     */
    public String getuAge() {
        return uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_age
     *
     * @param uAge the value for t_user.u_age
     *
     * @mbggenerated
     */
    public void setuAge(String uAge) {
        this.uAge = uAge == null ? null : uAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_class
     *
     * @return the value of t_user.u_class
     *
     * @mbggenerated
     */
    public Integer getuClass() {
        return uClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_class
     *
     * @param uClass the value for t_user.u_class
     *
     * @mbggenerated
     */
    public void setuClass(Integer uClass) {
        this.uClass = uClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CREATE_DT
     *
     * @return the value of t_user.CREATE_DT
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CREATE_DT
     *
     * @param createDt the value for t_user.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CREATE_OP
     *
     * @return the value of t_user.CREATE_OP
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CREATE_OP
     *
     * @param createOp the value for t_user.CREATE_OP
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CREATE_PG
     *
     * @return the value of t_user.CREATE_PG
     *
     * @mbggenerated
     */
    public String getCreatePg() {
        return createPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CREATE_PG
     *
     * @param createPg the value for t_user.CREATE_PG
     *
     * @mbggenerated
     */
    public void setCreatePg(String createPg) {
        this.createPg = createPg == null ? null : createPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UPDATE_DT
     *
     * @return the value of t_user.UPDATE_DT
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UPDATE_DT
     *
     * @param updateDt the value for t_user.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UPDATE_OP
     *
     * @return the value of t_user.UPDATE_OP
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UPDATE_OP
     *
     * @param updateOp the value for t_user.UPDATE_OP
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UPDATE_PG
     *
     * @return the value of t_user.UPDATE_PG
     *
     * @mbggenerated
     */
    public String getUpdatePg() {
        return updatePg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UPDATE_PG
     *
     * @param updatePg the value for t_user.UPDATE_PG
     *
     * @mbggenerated
     */
    public void setUpdatePg(String updatePg) {
        this.updatePg = updatePg == null ? null : updatePg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.VERSION
     *
     * @return the value of t_user.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.VERSION
     *
     * @param version the value for t_user.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}