package com.ltkj.app.common.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_code
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.org_id
     *
     * @mbggenerated
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_fid
     *
     * @mbggenerated
     */
    private String userFid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_fname
     *
     * @mbggenerated
     */
    private String userFname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_system
     *
     * @mbggenerated
     */
    private String isSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_remove
     *
     * @mbggenerated
     */
    private String isRemove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login_ip
     *
     * @mbggenerated
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.cut_off_date
     *
     * @mbggenerated
     */
    private Date cutOffDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_enabled
     *
     * @mbggenerated
     */
    private String isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_account_non_expired
     *
     * @mbggenerated
     */
    private String isAccountNonExpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_account_nonL_locked
     *
     * @mbggenerated
     */
    private String isAccountNonlLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_credentials_non_expired
     *
     * @mbggenerated
     */
    private String isCredentialsNonExpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name_eng
     *
     * @mbggenerated
     */
    private String nameEng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone_2
     *
     * @mbggenerated
     */
    private String phone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.msm_1
     *
     * @mbggenerated
     */
    private String msm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.msm_2
     *
     * @mbggenerated
     */
    private String msm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.alppha_cd
     *
     * @mbggenerated
     */
    private String alpphaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.work_years
     *
     * @mbggenerated
     */
    private Integer workYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.comment_1
     *
     * @mbggenerated
     */
    private String comment1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.comment_2
     *
     * @mbggenerated
     */
    private String comment2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_op
     *
     * @mbggenerated
     */
    private String createOp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_op
     *
     * @mbggenerated
     */
    private String updateOp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_code
     *
     * @return the value of sys_user.user_code
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_code
     *
     * @param userCode the value for sys_user.user_code
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_password
     *
     * @return the value of sys_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_password
     *
     * @param userPassword the value for sys_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.org_id
     *
     * @return the value of sys_user.org_id
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.org_id
     *
     * @param orgId the value for sys_user.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.org_name
     *
     * @return the value of sys_user.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.org_name
     *
     * @param orgName the value for sys_user.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_fid
     *
     * @return the value of sys_user.user_fid
     *
     * @mbggenerated
     */
    public String getUserFid() {
        return userFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_fid
     *
     * @param userFid the value for sys_user.user_fid
     *
     * @mbggenerated
     */
    public void setUserFid(String userFid) {
        this.userFid = userFid == null ? null : userFid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_fname
     *
     * @return the value of sys_user.user_fname
     *
     * @mbggenerated
     */
    public String getUserFname() {
        return userFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_fname
     *
     * @param userFname the value for sys_user.user_fname
     *
     * @mbggenerated
     */
    public void setUserFname(String userFname) {
        this.userFname = userFname == null ? null : userFname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_system
     *
     * @return the value of sys_user.is_system
     *
     * @mbggenerated
     */
    public String getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_system
     *
     * @param isSystem the value for sys_user.is_system
     *
     * @mbggenerated
     */
    public void setIsSystem(String isSystem) {
        this.isSystem = isSystem == null ? null : isSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_remove
     *
     * @return the value of sys_user.is_remove
     *
     * @mbggenerated
     */
    public String getIsRemove() {
        return isRemove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_remove
     *
     * @param isRemove the value for sys_user.is_remove
     *
     * @mbggenerated
     */
    public void setIsRemove(String isRemove) {
        this.isRemove = isRemove == null ? null : isRemove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_login_time
     *
     * @return the value of sys_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_login_time
     *
     * @param lastLoginTime the value for sys_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_login_ip
     *
     * @return the value of sys_user.last_login_ip
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_login_ip
     *
     * @param lastLoginIp the value for sys_user.last_login_ip
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.cut_off_date
     *
     * @return the value of sys_user.cut_off_date
     *
     * @mbggenerated
     */
    public Date getCutOffDate() {
        return cutOffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.cut_off_date
     *
     * @param cutOffDate the value for sys_user.cut_off_date
     *
     * @mbggenerated
     */
    public void setCutOffDate(Date cutOffDate) {
        this.cutOffDate = cutOffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_user
     *
     * @return the value of sys_user.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_user
     *
     * @param createUser the value for sys_user.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_user
     *
     * @return the value of sys_user.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_user
     *
     * @param updateUser the value for sys_user.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_enabled
     *
     * @return the value of sys_user.is_enabled
     *
     * @mbggenerated
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_enabled
     *
     * @param isEnabled the value for sys_user.is_enabled
     *
     * @mbggenerated
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled == null ? null : isEnabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_account_non_expired
     *
     * @return the value of sys_user.is_account_non_expired
     *
     * @mbggenerated
     */
    public String getIsAccountNonExpired() {
        return isAccountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_account_non_expired
     *
     * @param isAccountNonExpired the value for sys_user.is_account_non_expired
     *
     * @mbggenerated
     */
    public void setIsAccountNonExpired(String isAccountNonExpired) {
        this.isAccountNonExpired = isAccountNonExpired == null ? null : isAccountNonExpired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_account_nonL_locked
     *
     * @return the value of sys_user.is_account_nonL_locked
     *
     * @mbggenerated
     */
    public String getIsAccountNonlLocked() {
        return isAccountNonlLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_account_nonL_locked
     *
     * @param isAccountNonlLocked the value for sys_user.is_account_nonL_locked
     *
     * @mbggenerated
     */
    public void setIsAccountNonlLocked(String isAccountNonlLocked) {
        this.isAccountNonlLocked = isAccountNonlLocked == null ? null : isAccountNonlLocked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_credentials_non_expired
     *
     * @return the value of sys_user.is_credentials_non_expired
     *
     * @mbggenerated
     */
    public String getIsCredentialsNonExpired() {
        return isCredentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_credentials_non_expired
     *
     * @param isCredentialsNonExpired the value for sys_user.is_credentials_non_expired
     *
     * @mbggenerated
     */
    public void setIsCredentialsNonExpired(String isCredentialsNonExpired) {
        this.isCredentialsNonExpired = isCredentialsNonExpired == null ? null : isCredentialsNonExpired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.card_id
     *
     * @return the value of sys_user.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.card_id
     *
     * @param cardId the value for sys_user.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name_eng
     *
     * @return the value of sys_user.name_eng
     *
     * @mbggenerated
     */
    public String getNameEng() {
        return nameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name_eng
     *
     * @param nameEng the value for sys_user.name_eng
     *
     * @mbggenerated
     */
    public void setNameEng(String nameEng) {
        this.nameEng = nameEng == null ? null : nameEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone_2
     *
     * @return the value of sys_user.phone_2
     *
     * @mbggenerated
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone_2
     *
     * @param phone2 the value for sys_user.phone_2
     *
     * @mbggenerated
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.msm_1
     *
     * @return the value of sys_user.msm_1
     *
     * @mbggenerated
     */
    public String getMsm1() {
        return msm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.msm_1
     *
     * @param msm1 the value for sys_user.msm_1
     *
     * @mbggenerated
     */
    public void setMsm1(String msm1) {
        this.msm1 = msm1 == null ? null : msm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.msm_2
     *
     * @return the value of sys_user.msm_2
     *
     * @mbggenerated
     */
    public String getMsm2() {
        return msm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.msm_2
     *
     * @param msm2 the value for sys_user.msm_2
     *
     * @mbggenerated
     */
    public void setMsm2(String msm2) {
        this.msm2 = msm2 == null ? null : msm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.alppha_cd
     *
     * @return the value of sys_user.alppha_cd
     *
     * @mbggenerated
     */
    public String getAlpphaCd() {
        return alpphaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.alppha_cd
     *
     * @param alpphaCd the value for sys_user.alppha_cd
     *
     * @mbggenerated
     */
    public void setAlpphaCd(String alpphaCd) {
        this.alpphaCd = alpphaCd == null ? null : alpphaCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sex
     *
     * @return the value of sys_user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sex
     *
     * @param sex the value for sys_user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.age
     *
     * @return the value of sys_user.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.age
     *
     * @param age the value for sys_user.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.work_years
     *
     * @return the value of sys_user.work_years
     *
     * @mbggenerated
     */
    public Integer getWorkYears() {
        return workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.work_years
     *
     * @param workYears the value for sys_user.work_years
     *
     * @mbggenerated
     */
    public void setWorkYears(Integer workYears) {
        this.workYears = workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.comment_1
     *
     * @return the value of sys_user.comment_1
     *
     * @mbggenerated
     */
    public String getComment1() {
        return comment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.comment_1
     *
     * @param comment1 the value for sys_user.comment_1
     *
     * @mbggenerated
     */
    public void setComment1(String comment1) {
        this.comment1 = comment1 == null ? null : comment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.comment_2
     *
     * @return the value of sys_user.comment_2
     *
     * @mbggenerated
     */
    public String getComment2() {
        return comment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.comment_2
     *
     * @param comment2 the value for sys_user.comment_2
     *
     * @mbggenerated
     */
    public void setComment2(String comment2) {
        this.comment2 = comment2 == null ? null : comment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_op
     *
     * @return the value of sys_user.create_op
     *
     * @mbggenerated
     */
    public String getCreateOp() {
        return createOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_op
     *
     * @param createOp the value for sys_user.create_op
     *
     * @mbggenerated
     */
    public void setCreateOp(String createOp) {
        this.createOp = createOp == null ? null : createOp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_op
     *
     * @return the value of sys_user.update_op
     *
     * @mbggenerated
     */
    public String getUpdateOp() {
        return updateOp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_op
     *
     * @param updateOp the value for sys_user.update_op
     *
     * @mbggenerated
     */
    public void setUpdateOp(String updateOp) {
        this.updateOp = updateOp == null ? null : updateOp.trim();
    }
}