package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.BaseHashMap;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BaseHashMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_hash_map
     *
     * @mbggenerated
     */
    @Delete({
        "delete from m_hash_map",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_hash_map
     *
     * @mbggenerated
     */
    @Insert({
        "insert into m_hash_map (id, type_name, ",
        "key, value, is_remove)",
        "values (#{id,jdbcType=INTEGER}, #{typeName,jdbcType=VARCHAR}, ",
        "#{key,jdbcType=CHAR}, #{value,jdbcType=VARCHAR}, #{isRemove,jdbcType=CHAR})"
    })
    int insert(BaseHashMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_hash_map
     *
     * @mbggenerated
     */
    int insertSelective(BaseHashMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_hash_map
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, type_name, key, value, is_remove",
        "from m_hash_map",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    BaseHashMap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_hash_map
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseHashMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_hash_map
     *
     * @mbggenerated
     */
    @Update({
        "update m_hash_map",
        "set type_name = #{typeName,jdbcType=VARCHAR},",
          "key = #{key,jdbcType=CHAR},",
          "value = #{value,jdbcType=VARCHAR},",
          "is_remove = #{isRemove,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BaseHashMap record);
}