package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.BookType;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BookTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_book_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from q_book_type",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_book_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into q_book_type (uuid, type_code, ",
        "type_name, value)",
        "values (#{uuid,jdbcType=VARCHAR}, #{typeCode,jdbcType=VARCHAR}, ",
        "#{typeName,jdbcType=VARCHAR}, #{value,jdbcType=VARCHAR})"
    })
    int insert(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_book_type
     *
     * @mbggenerated
     */
    int insertSelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_book_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "uuid, type_code, type_name, value",
        "from q_book_type",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BookType selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_book_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_book_type
     *
     * @mbggenerated
     */
    @Update({
        "update q_book_type",
        "set type_code = #{typeCode,jdbcType=VARCHAR},",
          "type_name = #{typeName,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=VARCHAR}",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BookType record);
}