package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Books;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface BooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zwy_books
     *
     * @mbggenerated
     */
    @Delete({
        "delete from zwy_books",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zwy_books
     *
     * @mbggenerated
     */
    @Insert({
        "insert into zwy_books (uuid, book_number, ",
        "book_name, book_sort, ",
        "book_author, writer_id, book_price, pic_src, ",
        "book_discount, book_desc, ",
        "is_active, create_dt, ",
        "create_op, create_pg, ",
        "update_dt, update_op, ",
        "update_pg)",
        "values (#{uuid,jdbcType=VARCHAR}, #{bookNumber,jdbcType=VARCHAR}, ",
        "#{bookName,jdbcType=VARCHAR}, #{writerId,jdbcType=VARCHAR}, #{bookSort,jdbcType=CHAR}, ",
        "#{bookAuthor,jdbcType=VARCHAR}, #{bookPrice,jdbcType=DECIMAL}, #{picSrc,jdbcType=VARCHAR}, ",
        "#{bookDiscount,jdbcType=INTEGER}, #{bookDesc,jdbcType=VARCHAR}, ",
        "#{isActive,jdbcType=VARCHAR}, #{createDt,jdbcType=TIMESTAMP}, ",
        "#{createOp,jdbcType=VARCHAR}, #{createPg,jdbcType=VARCHAR}, ",
        "#{updateDt,jdbcType=TIMESTAMP}, #{updateOp,jdbcType=VARCHAR}, ",
        "#{updatePg,jdbcType=VARCHAR})"
    })
    int insert(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zwy_books
     *
     * @mbggenerated
     */
    int insertSelective(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zwy_books
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "uuid, book_number, book_name, book_sort, book_author,writer_id, book_price, pic_src, book_discount, ",
        "book_desc, is_active, create_dt, create_op, create_pg, update_dt, update_op, ",
        "update_pg",
        "from zwy_books",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Books selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zwy_books
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zwy_books
     *
     * @mbggenerated
     */
    @Update({
        "update zwy_books",
        "set book_number = #{bookNumber,jdbcType=VARCHAR},",
          "book_name = #{bookName,jdbcType=VARCHAR},",
          "book_sort = #{bookSort,jdbcType=CHAR},",
          "book_author = #{bookAuthor,jdbcType=VARCHAR},",
          "writer_id = #{writerId,jdbcType=VARCHAR},",
          "book_price = #{bookPrice,jdbcType=DECIMAL},",
          "pic_src = #{picSrc,jdbcType=VARCHAR},",      
          "book_discount = #{bookDiscount,jdbcType=INTEGER},",
          "book_desc = #{bookDesc,jdbcType=VARCHAR},",
          "is_active = #{isActive,jdbcType=VARCHAR},",
          "create_dt = #{createDt,jdbcType=TIMESTAMP},",
          "create_op = #{createOp,jdbcType=VARCHAR},",
          "create_pg = #{createPg,jdbcType=VARCHAR},",
          "update_dt = #{updateDt,jdbcType=TIMESTAMP},",
          "update_op = #{updateOp,jdbcType=VARCHAR},",
          "update_pg = #{updatePg,jdbcType=VARCHAR}",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Books record);
}