package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Cloth;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ClothMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_cloth
     *
     * @mbggenerated
     */
    @Delete({
        "delete from q_cloth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_cloth
     *
     * @mbggenerated
     */
    @Insert({
        "insert into q_cloth (id, clo_name, ",
        "clo_code, clo_brand, ",
        "clo_price, clo_size, ",
        "clo_color, description, ",
        "Is_Active, CREATE_DT, ",
        "CREATE_OP, CREATE_PG, ",
        "UPDATE_DT, UPDATE_OP, ",
        "UPDATE_PG)",
        "values (#{id,jdbcType=INTEGER}, #{cloName,jdbcType=VARCHAR}, ",
        "#{cloCode,jdbcType=VARCHAR}, #{cloBrand,jdbcType=VARCHAR}, ",
        "#{cloPrice,jdbcType=INTEGER}, #{cloSize,jdbcType=VARCHAR}, ",
        "#{cloColor,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{isActive,jdbcType=VARCHAR}, #{createDt,jdbcType=TIMESTAMP}, ",
        "#{createOp,jdbcType=VARCHAR}, #{createPg,jdbcType=VARCHAR}, ",
        "#{updateDt,jdbcType=TIMESTAMP}, #{updateOp,jdbcType=VARCHAR}, ",
        "#{updatePg,jdbcType=VARCHAR})"
    })
    int insert(Cloth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_cloth
     *
     * @mbggenerated
     */
    int insertSelective(Cloth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_cloth
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, clo_name, clo_code, clo_brand, clo_price, clo_size, clo_color, description, ",
        "Is_Active, CREATE_DT, CREATE_OP, CREATE_PG, UPDATE_DT, UPDATE_OP, UPDATE_PG",
        "from q_cloth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Cloth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_cloth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cloth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_cloth
     *
     * @mbggenerated
     */
    @Update({
        "update q_cloth",
        "set clo_name = #{cloName,jdbcType=VARCHAR},",
          "clo_code = #{cloCode,jdbcType=VARCHAR},",
          "clo_brand = #{cloBrand,jdbcType=VARCHAR},",
          "clo_price = #{cloPrice,jdbcType=INTEGER},",
          "clo_size = #{cloSize,jdbcType=VARCHAR},",
          "clo_color = #{cloColor,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "Is_Active = #{isActive,jdbcType=VARCHAR},",
          "CREATE_DT = #{createDt,jdbcType=TIMESTAMP},",
          "CREATE_OP = #{createOp,jdbcType=VARCHAR},",
          "CREATE_PG = #{createPg,jdbcType=VARCHAR},",
          "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
          "UPDATE_OP = #{updateOp,jdbcType=VARCHAR},",
          "UPDATE_PG = #{updatePg,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Cloth record);
}