package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Company;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_company",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_company (uuid, Company_Id, ",
        "Company_Name, Company_Name_E, ",
        "Short_Name, Short_Name_E, ",
        "Alpha_Cd, Legal_Person, ",
        "Register_Code, Is_Active, ",
        "CREATE_DT, CREATE_OP, ",
        "CREATE_PG, UPDATE_DT, ",
        "UPDATE_OP, UPDATE_PG)",
        "values (#{uuid,jdbcType=VARCHAR}, #{companyId,jdbcType=VARCHAR}, ",
        "#{companyName,jdbcType=VARCHAR}, #{companyNameE,jdbcType=VARCHAR}, ",
        "#{shortName,jdbcType=VARCHAR}, #{shortNameE,jdbcType=VARCHAR}, ",
        "#{alphaCd,jdbcType=VARCHAR}, #{legalPerson,jdbcType=VARCHAR}, ",
        "#{registerCode,jdbcType=VARCHAR}, #{isActive,jdbcType=VARCHAR}, ",
        "#{createDt,jdbcType=TIMESTAMP}, #{createOp,jdbcType=VARCHAR}, ",
        "#{createPg,jdbcType=VARCHAR}, #{updateDt,jdbcType=TIMESTAMP}, ",
        "#{updateOp,jdbcType=VARCHAR}, #{updatePg,jdbcType=VARCHAR})"
    })
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "uuid, Company_Id, Company_Name, Company_Name_E, Short_Name, Short_Name_E, Alpha_Cd, ",
        "Legal_Person, Register_Code, Is_Active, CREATE_DT, CREATE_OP, CREATE_PG, UPDATE_DT, ",
        "UPDATE_OP, UPDATE_PG",
        "from sys_company",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Company selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    @Update({
        "update sys_company",
        "set Company_Id = #{companyId,jdbcType=VARCHAR},",
          "Company_Name = #{companyName,jdbcType=VARCHAR},",
          "Company_Name_E = #{companyNameE,jdbcType=VARCHAR},",
          "Short_Name = #{shortName,jdbcType=VARCHAR},",
          "Short_Name_E = #{shortNameE,jdbcType=VARCHAR},",
          "Alpha_Cd = #{alphaCd,jdbcType=VARCHAR},",
          "Legal_Person = #{legalPerson,jdbcType=VARCHAR},",
          "Register_Code = #{registerCode,jdbcType=VARCHAR},",
          "Is_Active = #{isActive,jdbcType=VARCHAR},",
          "CREATE_DT = #{createDt,jdbcType=TIMESTAMP},",
          "CREATE_OP = #{createOp,jdbcType=VARCHAR},",
          "CREATE_PG = #{createPg,jdbcType=VARCHAR},",
          "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
          "UPDATE_OP = #{updateOp,jdbcType=VARCHAR},",
          "UPDATE_PG = #{updatePg,jdbcType=VARCHAR}",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Company record);
}