package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.GeBytearray;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GeBytearrayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_ge_bytearray",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_ge_bytearray (ID_, REV_, ",
        "NAME_, DEPLOYMENT_ID_, ",
        "GENERATED_, BYTES_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{deploymentId,jdbcType=VARCHAR}, ",
        "#{generated,jdbcType=TINYINT}, #{bytes,jdbcType=LONGVARBINARY})"
    })
    int insert(GeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbggenerated
     */
    int insertSelective(GeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, NAME_, DEPLOYMENT_ID_, GENERATED_, BYTES_",
        "from act_ge_bytearray",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    GeBytearray selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbggenerated
     */
    @Update({
        "update act_ge_bytearray",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "NAME_ = #{name,jdbcType=VARCHAR},",
          "DEPLOYMENT_ID_ = #{deploymentId,jdbcType=VARCHAR},",
          "GENERATED_ = #{generated,jdbcType=TINYINT},",
          "BYTES_ = #{bytes,jdbcType=LONGVARBINARY}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(GeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbggenerated
     */
    @Update({
        "update act_ge_bytearray",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "NAME_ = #{name,jdbcType=VARCHAR},",
          "DEPLOYMENT_ID_ = #{deploymentId,jdbcType=VARCHAR},",
          "GENERATED_ = #{generated,jdbcType=TINYINT}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GeBytearray record);
}