package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.GeProperty;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GePropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_ge_property",
        "where NAME_ = #{name,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_ge_property (NAME_, VALUE_, ",
        "REV_)",
        "values (#{name,jdbcType=VARCHAR}, #{value,jdbcType=VARCHAR}, ",
        "#{rev,jdbcType=INTEGER})"
    })
    int insert(GeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbggenerated
     */
    int insertSelective(GeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "NAME_, VALUE_, REV_",
        "from act_ge_property",
        "where NAME_ = #{name,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    GeProperty selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbggenerated
     */
    @Update({
        "update act_ge_property",
        "set VALUE_ = #{value,jdbcType=VARCHAR},",
          "REV_ = #{rev,jdbcType=INTEGER}",
        "where NAME_ = #{name,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GeProperty record);
}