package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Goods;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goods
     *
     * @mbggenerated
     */
    @Delete({
        "delete from s_goods",
        "where goods_id = #{goodsId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goods
     *
     * @mbggenerated
     */
    @Insert({
        "insert into s_goods (goods_id, company_id, ",
        "goods_name, spec, ",
        "batch_code, primary_category, ",
        "small_category, weight, ",
        "pic_src, description, ",
        "buying_price, selling_price1, ",
        "selling_price2, selling_price3, ",
        "discount, quantity, ",
        "replenish, key_cd, ",
        "Is_Active, CREATE_DT, ",
        "CREATE_OP, CREATE_PG, ",
        "UPDATE_DT, UPDATE_OP, ",
        "UPDATE_PG)",
        "values (#{goodsId,jdbcType=VARCHAR}, #{companyId,jdbcType=VARCHAR}, ",
        "#{goodsName,jdbcType=VARCHAR}, #{spec,jdbcType=VARCHAR}, ",
        "#{batchCode,jdbcType=VARCHAR}, #{primaryCategory,jdbcType=CHAR}, ",
        "#{smallCategory,jdbcType=CHAR}, #{weight,jdbcType=DECIMAL}, ",
        "#{picSrc,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{buyingPrice,jdbcType=DECIMAL}, #{sellingPrice1,jdbcType=DECIMAL}, ",
        "#{sellingPrice2,jdbcType=DECIMAL}, #{sellingPrice3,jdbcType=DECIMAL}, ",
        "#{discount,jdbcType=INTEGER}, #{quantity,jdbcType=INTEGER}, ",
        "#{replenish,jdbcType=INTEGER}, #{keyCd,jdbcType=VARCHAR}, ",
        "#{isActive,jdbcType=VARCHAR}, #{createDt,jdbcType=TIMESTAMP}, ",
        "#{createOp,jdbcType=VARCHAR}, #{createPg,jdbcType=VARCHAR}, ",
        "#{updateDt,jdbcType=TIMESTAMP}, #{updateOp,jdbcType=VARCHAR}, ",
        "#{updatePg,jdbcType=VARCHAR})"
    })
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goods
     *
     * @mbggenerated
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goods
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "goods_id, company_id, goods_name, spec, batch_code, primary_category, small_category, ",
        "weight, pic_src, description, buying_price, selling_price1, selling_price2, ",
        "selling_price3, discount, quantity, replenish, key_cd, Is_Active, CREATE_DT, ",
        "CREATE_OP, CREATE_PG, UPDATE_DT, UPDATE_OP, UPDATE_PG",
        "from s_goods",
        "where goods_id = #{goodsId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Goods selectByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_goods
     *
     * @mbggenerated
     */
    @Update({
        "update s_goods",
        "set company_id = #{companyId,jdbcType=VARCHAR},",
          "goods_name = #{goodsName,jdbcType=VARCHAR},",
          "spec = #{spec,jdbcType=VARCHAR},",
          "batch_code = #{batchCode,jdbcType=VARCHAR},",
          "primary_category = #{primaryCategory,jdbcType=CHAR},",
          "small_category = #{smallCategory,jdbcType=CHAR},",
          "weight = #{weight,jdbcType=DECIMAL},",
          "pic_src = #{picSrc,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "buying_price = #{buyingPrice,jdbcType=DECIMAL},",
          "selling_price1 = #{sellingPrice1,jdbcType=DECIMAL},",
          "selling_price2 = #{sellingPrice2,jdbcType=DECIMAL},",
          "selling_price3 = #{sellingPrice3,jdbcType=DECIMAL},",
          "discount = #{discount,jdbcType=INTEGER},",
          "quantity = #{quantity,jdbcType=INTEGER},",
          "replenish = #{replenish,jdbcType=INTEGER},",
          "key_cd = #{keyCd,jdbcType=VARCHAR},",
          "Is_Active = #{isActive,jdbcType=VARCHAR},",
          "CREATE_DT = #{createDt,jdbcType=TIMESTAMP},",
          "CREATE_OP = #{createOp,jdbcType=VARCHAR},",
          "CREATE_PG = #{createPg,jdbcType=VARCHAR},",
          "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
          "UPDATE_OP = #{updateOp,jdbcType=VARCHAR},",
          "UPDATE_PG = #{updatePg,jdbcType=VARCHAR}",
        "where goods_id = #{goodsId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Goods record);
}