package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.HiActinst;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HiActinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_hi_actinst",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_hi_actinst (ID_, PROC_DEF_ID_, ",
        "PROC_INST_ID_, EXECUTION_ID_, ",
        "ACT_ID_, TASK_ID_, CALL_PROC_INST_ID_, ",
        "ACT_NAME_, ACT_TYPE_, ",
        "ASSIGNEE_, START_TIME_, ",
        "END_TIME_, DURATION_, ",
        "TENANT_ID_)",
        "values (#{id,jdbcType=VARCHAR}, #{procDefId,jdbcType=VARCHAR}, ",
        "#{procInstId,jdbcType=VARCHAR}, #{executionId,jdbcType=VARCHAR}, ",
        "#{actId,jdbcType=VARCHAR}, #{taskId,jdbcType=VARCHAR}, #{callProcInstId,jdbcType=VARCHAR}, ",
        "#{actName,jdbcType=VARCHAR}, #{actType,jdbcType=VARCHAR}, ",
        "#{assignee,jdbcType=VARCHAR}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{duration,jdbcType=BIGINT}, ",
        "#{tenantId,jdbcType=VARCHAR})"
    })
    int insert(HiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbggenerated
     */
    int insertSelective(HiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, PROC_DEF_ID_, PROC_INST_ID_, EXECUTION_ID_, ACT_ID_, TASK_ID_, CALL_PROC_INST_ID_, ",
        "ACT_NAME_, ACT_TYPE_, ASSIGNEE_, START_TIME_, END_TIME_, DURATION_, TENANT_ID_",
        "from act_hi_actinst",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    HiActinst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbggenerated
     */
    @Update({
        "update act_hi_actinst",
        "set PROC_DEF_ID_ = #{procDefId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "EXECUTION_ID_ = #{executionId,jdbcType=VARCHAR},",
          "ACT_ID_ = #{actId,jdbcType=VARCHAR},",
          "TASK_ID_ = #{taskId,jdbcType=VARCHAR},",
          "CALL_PROC_INST_ID_ = #{callProcInstId,jdbcType=VARCHAR},",
          "ACT_NAME_ = #{actName,jdbcType=VARCHAR},",
          "ACT_TYPE_ = #{actType,jdbcType=VARCHAR},",
          "ASSIGNEE_ = #{assignee,jdbcType=VARCHAR},",
          "START_TIME_ = #{startTime,jdbcType=TIMESTAMP},",
          "END_TIME_ = #{endTime,jdbcType=TIMESTAMP},",
          "DURATION_ = #{duration,jdbcType=BIGINT},",
          "TENANT_ID_ = #{tenantId,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(HiActinst record);
}