package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.HiAttachment;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HiAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_attachment
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_hi_attachment",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_attachment
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_hi_attachment (ID_, REV_, ",
        "USER_ID_, NAME_, DESCRIPTION_, ",
        "TYPE_, TASK_ID_, PROC_INST_ID_, ",
        "URL_, CONTENT_ID_, ",
        "TIME_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{taskId,jdbcType=VARCHAR}, #{procInstId,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{contentId,jdbcType=VARCHAR}, ",
        "#{time,jdbcType=TIMESTAMP})"
    })
    int insert(HiAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_attachment
     *
     * @mbggenerated
     */
    int insertSelective(HiAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_attachment
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, USER_ID_, NAME_, DESCRIPTION_, TYPE_, TASK_ID_, PROC_INST_ID_, URL_, ",
        "CONTENT_ID_, TIME_",
        "from act_hi_attachment",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    HiAttachment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HiAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_attachment
     *
     * @mbggenerated
     */
    @Update({
        "update act_hi_attachment",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "USER_ID_ = #{userId,jdbcType=VARCHAR},",
          "NAME_ = #{name,jdbcType=VARCHAR},",
          "DESCRIPTION_ = #{description,jdbcType=VARCHAR},",
          "TYPE_ = #{type,jdbcType=VARCHAR},",
          "TASK_ID_ = #{taskId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "URL_ = #{url,jdbcType=VARCHAR},",
          "CONTENT_ID_ = #{contentId,jdbcType=VARCHAR},",
          "TIME_ = #{time,jdbcType=TIMESTAMP}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(HiAttachment record);
}