package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.HiComment;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HiCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_hi_comment",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_hi_comment (ID_, TYPE_, ",
        "TIME_, USER_ID_, ",
        "TASK_ID_, PROC_INST_ID_, ",
        "ACTION_, MESSAGE_, ",
        "FULL_MSG_)",
        "values (#{id,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
        "#{time,jdbcType=TIMESTAMP}, #{userId,jdbcType=VARCHAR}, ",
        "#{taskId,jdbcType=VARCHAR}, #{procInstId,jdbcType=VARCHAR}, ",
        "#{action,jdbcType=VARCHAR}, #{message,jdbcType=VARCHAR}, ",
        "#{fullMsg,jdbcType=LONGVARBINARY})"
    })
    int insert(HiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbggenerated
     */
    int insertSelective(HiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, TYPE_, TIME_, USER_ID_, TASK_ID_, PROC_INST_ID_, ACTION_, MESSAGE_, FULL_MSG_",
        "from act_hi_comment",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    HiComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbggenerated
     */
    @Update({
        "update act_hi_comment",
        "set TYPE_ = #{type,jdbcType=VARCHAR},",
          "TIME_ = #{time,jdbcType=TIMESTAMP},",
          "USER_ID_ = #{userId,jdbcType=VARCHAR},",
          "TASK_ID_ = #{taskId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "ACTION_ = #{action,jdbcType=VARCHAR},",
          "MESSAGE_ = #{message,jdbcType=VARCHAR},",
          "FULL_MSG_ = #{fullMsg,jdbcType=LONGVARBINARY}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(HiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbggenerated
     */
    @Update({
        "update act_hi_comment",
        "set TYPE_ = #{type,jdbcType=VARCHAR},",
          "TIME_ = #{time,jdbcType=TIMESTAMP},",
          "USER_ID_ = #{userId,jdbcType=VARCHAR},",
          "TASK_ID_ = #{taskId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "ACTION_ = #{action,jdbcType=VARCHAR},",
          "MESSAGE_ = #{message,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(HiComment record);
}