package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.HiIdentitylink;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HiIdentitylinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_hi_identitylink",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_hi_identitylink (ID_, GROUP_ID_, ",
        "TYPE_, USER_ID_, TASK_ID_, ",
        "PROC_INST_ID_)",
        "values (#{id,jdbcType=VARCHAR}, #{groupId,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, #{taskId,jdbcType=VARCHAR}, ",
        "#{procInstId,jdbcType=VARCHAR})"
    })
    int insert(HiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbggenerated
     */
    int insertSelective(HiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, GROUP_ID_, TYPE_, USER_ID_, TASK_ID_, PROC_INST_ID_",
        "from act_hi_identitylink",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    HiIdentitylink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbggenerated
     */
    @Update({
        "update act_hi_identitylink",
        "set GROUP_ID_ = #{groupId,jdbcType=VARCHAR},",
          "TYPE_ = #{type,jdbcType=VARCHAR},",
          "USER_ID_ = #{userId,jdbcType=VARCHAR},",
          "TASK_ID_ = #{taskId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(HiIdentitylink record);
}