package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.HiProcinst;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HiProcinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_hi_procinst",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_hi_procinst (ID_, PROC_INST_ID_, ",
        "BUSINESS_KEY_, PROC_DEF_ID_, ",
        "START_TIME_, END_TIME_, ",
        "DURATION_, START_USER_ID_, ",
        "START_ACT_ID_, END_ACT_ID_, ",
        "SUPER_PROCESS_INSTANCE_ID_, DELETE_REASON_, ",
        "TENANT_ID_, NAME_)",
        "values (#{id,jdbcType=VARCHAR}, #{procInstId,jdbcType=VARCHAR}, ",
        "#{businessKey,jdbcType=VARCHAR}, #{procDefId,jdbcType=VARCHAR}, ",
        "#{startTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{duration,jdbcType=BIGINT}, #{startUserId,jdbcType=VARCHAR}, ",
        "#{startActId,jdbcType=VARCHAR}, #{endActId,jdbcType=VARCHAR}, ",
        "#{superProcessInstanceId,jdbcType=VARCHAR}, #{deleteReason,jdbcType=VARCHAR}, ",
        "#{tenantId,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR})"
    })
    int insert(HiProcinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbggenerated
     */
    int insertSelective(HiProcinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, PROC_INST_ID_, BUSINESS_KEY_, PROC_DEF_ID_, START_TIME_, END_TIME_, DURATION_, ",
        "START_USER_ID_, START_ACT_ID_, END_ACT_ID_, SUPER_PROCESS_INSTANCE_ID_, DELETE_REASON_, ",
        "TENANT_ID_, NAME_",
        "from act_hi_procinst",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    HiProcinst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HiProcinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbggenerated
     */
    @Update({
        "update act_hi_procinst",
        "set PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "BUSINESS_KEY_ = #{businessKey,jdbcType=VARCHAR},",
          "PROC_DEF_ID_ = #{procDefId,jdbcType=VARCHAR},",
          "START_TIME_ = #{startTime,jdbcType=TIMESTAMP},",
          "END_TIME_ = #{endTime,jdbcType=TIMESTAMP},",
          "DURATION_ = #{duration,jdbcType=BIGINT},",
          "START_USER_ID_ = #{startUserId,jdbcType=VARCHAR},",
          "START_ACT_ID_ = #{startActId,jdbcType=VARCHAR},",
          "END_ACT_ID_ = #{endActId,jdbcType=VARCHAR},",
          "SUPER_PROCESS_INSTANCE_ID_ = #{superProcessInstanceId,jdbcType=VARCHAR},",
          "DELETE_REASON_ = #{deleteReason,jdbcType=VARCHAR},",
          "TENANT_ID_ = #{tenantId,jdbcType=VARCHAR},",
          "NAME_ = #{name,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(HiProcinst record);
}