package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.IdGroup;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface IdGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_id_group",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_id_group (ID_, REV_, ",
        "NAME_, TYPE_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR})"
    })
    int insert(IdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbggenerated
     */
    int insertSelective(IdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, NAME_, TYPE_",
        "from act_id_group",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    IdGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_group
     *
     * @mbggenerated
     */
    @Update({
        "update act_id_group",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "NAME_ = #{name,jdbcType=VARCHAR},",
          "TYPE_ = #{type,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IdGroup record);
}