package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.LeaveBill;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface LeaveBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_leave_bill
     *
     * @mbggenerated
     */
    @Delete({
        "delete from s_leave_bill",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_leave_bill
     *
     * @mbggenerated
     */
    @Insert({
        "insert into s_leave_bill (id, leave_type, ",
        "from_time, end_time, ",
        "days, comments, ",
        "state, user_id, create_user, ",
        "create_time, update_user, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{leaveType,jdbcType=CHAR}, ",
        "#{fromTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{days,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=CHAR}, #{userId,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(LeaveBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_leave_bill
     *
     * @mbggenerated
     */
    int insertSelective(LeaveBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_leave_bill
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, leave_type, from_time, end_time, days, comments, state, user_id, create_user, ",
        "create_time, update_user, update_time",
        "from s_leave_bill",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    LeaveBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_leave_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LeaveBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_leave_bill
     *
     * @mbggenerated
     */
    @Update({
        "update s_leave_bill",
        "set leave_type = #{leaveType,jdbcType=CHAR},",
          "from_time = #{fromTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "days = #{days,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=CHAR},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LeaveBill record);
}