package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Log;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_log (id, description, ",
        "exception_code, type, ",
        "exception_detail, method, ",
        "params, create_by, ",
        "create_time, request_ip)",
        "values (#{id,jdbcType=INTEGER}, #{description,jdbcType=VARCHAR}, ",
        "#{exceptionCode,jdbcType=VARCHAR}, #{type,jdbcType=CHAR}, ",
        "#{exceptionDetail,jdbcType=VARCHAR}, #{method,jdbcType=VARCHAR}, ",
        "#{params,jdbcType=VARCHAR}, #{createBy,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{requestIp,jdbcType=VARCHAR})"
    })
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, description, exception_code, type, exception_detail, method, params, create_by, ",
        "create_time, request_ip",
        "from sys_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Log selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    @Update({
        "update sys_log",
        "set description = #{description,jdbcType=VARCHAR},",
          "exception_code = #{exceptionCode,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=CHAR},",
          "exception_detail = #{exceptionDetail,jdbcType=VARCHAR},",
          "method = #{method,jdbcType=VARCHAR},",
          "params = #{params,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "request_ip = #{requestIp,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Log record);
}