package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Mast;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_master
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_master",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_master
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_master (uuid, Company_Id, ",
        "Catgory_Id1, Catgory_Id2, ",
        "Catgory_Id3, Catgory_Id4, ",
        "Category, Key_Cd, ",
        "Key_Value, Disp_Order, ",
        "Description, Comment1, ",
        "Comment2, Is_Active, ",
        "Is_Display, CREATE_DT, ",
        "CREATE_OP, CREATE_PG, ",
        "UPDATE_DT, UPDATE_OP, ",
        "UPDATE_PG)",
        "values (#{uuid,jdbcType=VARCHAR}, #{companyId,jdbcType=VARCHAR}, ",
        "#{catgoryId1,jdbcType=VARCHAR}, #{catgoryId2,jdbcType=VARCHAR}, ",
        "#{catgoryId3,jdbcType=VARCHAR}, #{catgoryId4,jdbcType=VARCHAR}, ",
        "#{category,jdbcType=VARCHAR}, #{keyCd,jdbcType=VARCHAR}, ",
        "#{keyValue,jdbcType=VARCHAR}, #{dispOrder,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{comment1,jdbcType=VARCHAR}, ",
        "#{comment2,jdbcType=VARCHAR}, #{isActive,jdbcType=VARCHAR}, ",
        "#{isDisplay,jdbcType=VARCHAR}, #{createDt,jdbcType=TIMESTAMP}, ",
        "#{createOp,jdbcType=VARCHAR}, #{createPg,jdbcType=VARCHAR}, ",
        "#{updateDt,jdbcType=TIMESTAMP}, #{updateOp,jdbcType=VARCHAR}, ",
        "#{updatePg,jdbcType=VARCHAR})"
    })
    int insert(Mast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_master
     *
     * @mbggenerated
     */
    int insertSelective(Mast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_master
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "uuid, Company_Id, Catgory_Id1, Catgory_Id2, Catgory_Id3, Catgory_Id4, Category, ",
        "Key_Cd, Key_Value, Disp_Order, Description, Comment1, Comment2, Is_Active, Is_Display, ",
        "CREATE_DT, CREATE_OP, CREATE_PG, UPDATE_DT, UPDATE_OP, UPDATE_PG",
        "from t_master",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Mast selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_master
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_master
     *
     * @mbggenerated
     */
    @Update({
        "update t_master",
        "set Company_Id = #{companyId,jdbcType=VARCHAR},",
          "Catgory_Id1 = #{catgoryId1,jdbcType=VARCHAR},",
          "Catgory_Id2 = #{catgoryId2,jdbcType=VARCHAR},",
          "Catgory_Id3 = #{catgoryId3,jdbcType=VARCHAR},",
          "Catgory_Id4 = #{catgoryId4,jdbcType=VARCHAR},",
          "Category = #{category,jdbcType=VARCHAR},",
          "Key_Cd = #{keyCd,jdbcType=VARCHAR},",
          "Key_Value = #{keyValue,jdbcType=VARCHAR},",
          "Disp_Order = #{dispOrder,jdbcType=INTEGER},",
          "Description = #{description,jdbcType=VARCHAR},",
          "Comment1 = #{comment1,jdbcType=VARCHAR},",
          "Comment2 = #{comment2,jdbcType=VARCHAR},",
          "Is_Active = #{isActive,jdbcType=VARCHAR},",
          "Is_Display = #{isDisplay,jdbcType=VARCHAR},",
          "CREATE_DT = #{createDt,jdbcType=TIMESTAMP},",
          "CREATE_OP = #{createOp,jdbcType=VARCHAR},",
          "CREATE_PG = #{createPg,jdbcType=VARCHAR},",
          "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
          "UPDATE_OP = #{updateOp,jdbcType=VARCHAR},",
          "UPDATE_PG = #{updatePg,jdbcType=VARCHAR}",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Mast record);
}