package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.NotInh;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface NotInhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_not_inh
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_not_inh",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_not_inh
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_not_inh (id, set_org_id, ",
        "set_org_fid, user_role_id)",
        "values (#{id,jdbcType=INTEGER}, #{setOrgId,jdbcType=VARCHAR}, ",
        "#{setOrgFid,jdbcType=VARCHAR}, #{userRoleId,jdbcType=INTEGER})"
    })
    int insert(NotInh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_not_inh
     *
     * @mbggenerated
     */
    int insertSelective(NotInh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_not_inh
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, set_org_id, set_org_fid, user_role_id",
        "from sys_not_inh",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    NotInh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_not_inh
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NotInh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_not_inh
     *
     * @mbggenerated
     */
    @Update({
        "update sys_not_inh",
        "set set_org_id = #{setOrgId,jdbcType=VARCHAR},",
          "set_org_fid = #{setOrgFid,jdbcType=VARCHAR},",
          "user_role_id = #{userRoleId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(NotInh record);
}