package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Order;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order
     *
     * @mbggenerated
     */
    @Delete({
        "delete from s_order",
        "where order_id = #{orderId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order
     *
     * @mbggenerated
     */
    @Insert({
        "insert into s_order (order_id, company_id, ",
        "department_id, department_name, ",
        "customer_id, customer_name, ",
        "customer_phone, goods_price, ",
        "postage, order_price, ",
        "status, description, ",
        "Is_Active, CREATE_DT, ",
        "CREATE_OP, CREATE_PG, ",
        "UPDATE_DT, UPDATE_OP, ",
        "UPDATE_PG)",
        "values (#{orderId,jdbcType=VARCHAR}, #{companyId,jdbcType=VARCHAR}, ",
        "#{departmentId,jdbcType=VARCHAR}, #{departmentName,jdbcType=VARCHAR}, ",
        "#{customerId,jdbcType=VARCHAR}, #{customerName,jdbcType=VARCHAR}, ",
        "#{customerPhone,jdbcType=VARCHAR}, #{goodsPrice,jdbcType=DECIMAL}, ",
        "#{postage,jdbcType=DECIMAL}, #{orderPrice,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=CHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{isActive,jdbcType=VARCHAR}, #{createDt,jdbcType=TIMESTAMP}, ",
        "#{createOp,jdbcType=VARCHAR}, #{createPg,jdbcType=VARCHAR}, ",
        "#{updateDt,jdbcType=TIMESTAMP}, #{updateOp,jdbcType=VARCHAR}, ",
        "#{updatePg,jdbcType=VARCHAR})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "order_id, company_id, department_id, department_name, customer_id, customer_name, ",
        "customer_phone, goods_price, postage, order_price, status, description, Is_Active, ",
        "CREATE_DT, CREATE_OP, CREATE_PG, UPDATE_DT, UPDATE_OP, UPDATE_PG",
        "from s_order",
        "where order_id = #{orderId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Order selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order
     *
     * @mbggenerated
     */
    @Update({
        "update s_order",
        "set company_id = #{companyId,jdbcType=VARCHAR},",
          "department_id = #{departmentId,jdbcType=VARCHAR},",
          "department_name = #{departmentName,jdbcType=VARCHAR},",
          "customer_id = #{customerId,jdbcType=VARCHAR},",
          "customer_name = #{customerName,jdbcType=VARCHAR},",
          "customer_phone = #{customerPhone,jdbcType=VARCHAR},",
          "goods_price = #{goodsPrice,jdbcType=DECIMAL},",
          "postage = #{postage,jdbcType=DECIMAL},",
          "order_price = #{orderPrice,jdbcType=DECIMAL},",
          "status = #{status,jdbcType=CHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "Is_Active = #{isActive,jdbcType=VARCHAR},",
          "CREATE_DT = #{createDt,jdbcType=TIMESTAMP},",
          "CREATE_OP = #{createOp,jdbcType=VARCHAR},",
          "CREATE_PG = #{createPg,jdbcType=VARCHAR},",
          "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
          "UPDATE_OP = #{updateOp,jdbcType=VARCHAR},",
          "UPDATE_PG = #{updatePg,jdbcType=VARCHAR}",
        "where order_id = #{orderId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Order record);
}