package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.OrderDetail;
import com.ltkj.app.common.model.OrderDetailKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order_detail
     *
     * @mbggenerated
     */
    @Delete({
        "delete from s_order_detail",
        "where order_id = #{orderId,jdbcType=VARCHAR}",
          "and goods_id = #{goodsId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(OrderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order_detail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into s_order_detail (order_id, goods_id, ",
        "goods_name, spec, ",
        "buying_price, price, ",
        "quantity, order_num)",
        "values (#{orderId,jdbcType=VARCHAR}, #{goodsId,jdbcType=VARCHAR}, ",
        "#{goodsName,jdbcType=VARCHAR}, #{spec,jdbcType=VARCHAR}, ",
        "#{buyingPrice,jdbcType=DECIMAL}, #{price,jdbcType=DECIMAL}, ",
        "#{quantity,jdbcType=INTEGER}, #{orderNum,jdbcType=INTEGER})"
    })
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order_detail
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "order_id, goods_id, goods_name, spec, buying_price, price, quantity, order_num",
        "from s_order_detail",
        "where order_id = #{orderId,jdbcType=VARCHAR}",
          "and goods_id = #{goodsId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    OrderDetail selectByPrimaryKey(OrderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_order_detail
     *
     * @mbggenerated
     */
    @Update({
        "update s_order_detail",
        "set goods_name = #{goodsName,jdbcType=VARCHAR},",
          "spec = #{spec,jdbcType=VARCHAR},",
          "buying_price = #{buyingPrice,jdbcType=DECIMAL},",
          "price = #{price,jdbcType=DECIMAL},",
          "quantity = #{quantity,jdbcType=INTEGER},",
          "order_num = #{orderNum,jdbcType=INTEGER}",
        "where order_id = #{orderId,jdbcType=VARCHAR}",
          "and goods_id = #{goodsId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OrderDetail record);
}