package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Organizational;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrganizationalMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_org",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_org (id, org_name, ",
        "org_fId, org_fName, ",
        "org_level, org_type, ",
        "parent_id, comments, ",
        "is_remove, create_time, ",
        "create_user, update_time, ",
        "update_user)",
        "values (#{id,jdbcType=VARCHAR}, #{orgName,jdbcType=VARCHAR}, ",
        "#{orgFid,jdbcType=VARCHAR}, #{orgFname,jdbcType=VARCHAR}, ",
        "#{orgLevel,jdbcType=INTEGER}, #{orgType,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{isRemove,jdbcType=CHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createUser,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updateUser,jdbcType=VARCHAR})"
    })
    int insert(Organizational record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    int insertSelective(Organizational record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, org_name, org_fId, org_fName, org_level, org_type, parent_id, comments, ",
        "is_remove, create_time, create_user, update_time, update_user",
        "from sys_org",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Organizational selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Organizational record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    @Update({
        "update sys_org",
        "set org_name = #{orgName,jdbcType=VARCHAR},",
          "org_fId = #{orgFid,jdbcType=VARCHAR},",
          "org_fName = #{orgFname,jdbcType=VARCHAR},",
          "org_level = #{orgLevel,jdbcType=INTEGER},",
          "org_type = #{orgType,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=VARCHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "is_remove = #{isRemove,jdbcType=CHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Organizational record);
}