package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.ReDeployment;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReDeploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_re_deployment",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_re_deployment (ID_, NAME_, ",
        "CATEGORY_, TENANT_ID_, ",
        "DEPLOY_TIME_)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{category,jdbcType=VARCHAR}, #{tenantId,jdbcType=VARCHAR}, ",
        "#{deployTime,jdbcType=TIMESTAMP})"
    })
    int insert(ReDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbggenerated
     */
    int insertSelective(ReDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, NAME_, CATEGORY_, TENANT_ID_, DEPLOY_TIME_",
        "from act_re_deployment",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReDeployment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbggenerated
     */
    @Update({
        "update act_re_deployment",
        "set NAME_ = #{name,jdbcType=VARCHAR},",
          "CATEGORY_ = #{category,jdbcType=VARCHAR},",
          "TENANT_ID_ = #{tenantId,jdbcType=VARCHAR},",
          "DEPLOY_TIME_ = #{deployTime,jdbcType=TIMESTAMP}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReDeployment record);
}