package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.ReModel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_re_model",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_re_model (ID_, REV_, ",
        "NAME_, KEY_, CATEGORY_, ",
        "CREATE_TIME_, LAST_UPDATE_TIME_, ",
        "VERSION_, META_INFO_, ",
        "DEPLOYMENT_ID_, EDITOR_SOURCE_VALUE_ID_, ",
        "EDITOR_SOURCE_EXTRA_VALUE_ID_, TENANT_ID_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{key,jdbcType=VARCHAR}, #{category,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{lastUpdateTime,jdbcType=TIMESTAMP}, ",
        "#{version,jdbcType=INTEGER}, #{metaInfo,jdbcType=VARCHAR}, ",
        "#{deploymentId,jdbcType=VARCHAR}, #{editorSourceValueId,jdbcType=VARCHAR}, ",
        "#{editorSourceExtraValueId,jdbcType=VARCHAR}, #{tenantId,jdbcType=VARCHAR})"
    })
    int insert(ReModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbggenerated
     */
    int insertSelective(ReModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, NAME_, KEY_, CATEGORY_, CREATE_TIME_, LAST_UPDATE_TIME_, VERSION_, ",
        "META_INFO_, DEPLOYMENT_ID_, EDITOR_SOURCE_VALUE_ID_, EDITOR_SOURCE_EXTRA_VALUE_ID_, ",
        "TENANT_ID_",
        "from act_re_model",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbggenerated
     */
    @Update({
        "update act_re_model",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "NAME_ = #{name,jdbcType=VARCHAR},",
          "KEY_ = #{key,jdbcType=VARCHAR},",
          "CATEGORY_ = #{category,jdbcType=VARCHAR},",
          "CREATE_TIME_ = #{createTime,jdbcType=TIMESTAMP},",
          "LAST_UPDATE_TIME_ = #{lastUpdateTime,jdbcType=TIMESTAMP},",
          "VERSION_ = #{version,jdbcType=INTEGER},",
          "META_INFO_ = #{metaInfo,jdbcType=VARCHAR},",
          "DEPLOYMENT_ID_ = #{deploymentId,jdbcType=VARCHAR},",
          "EDITOR_SOURCE_VALUE_ID_ = #{editorSourceValueId,jdbcType=VARCHAR},",
          "EDITOR_SOURCE_EXTRA_VALUE_ID_ = #{editorSourceExtraValueId,jdbcType=VARCHAR},",
          "TENANT_ID_ = #{tenantId,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReModel record);
}