package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.ReProcdef;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReProcdefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_re_procdef",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_re_procdef (ID_, REV_, ",
        "CATEGORY_, NAME_, ",
        "KEY_, VERSION_, DEPLOYMENT_ID_, ",
        "RESOURCE_NAME_, DGRM_RESOURCE_NAME_, ",
        "DESCRIPTION_, HAS_START_FORM_KEY_, ",
        "HAS_GRAPHICAL_NOTATION_, SUSPENSION_STATE_, ",
        "TENANT_ID_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{category,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{key,jdbcType=VARCHAR}, #{version,jdbcType=INTEGER}, #{deploymentId,jdbcType=VARCHAR}, ",
        "#{resourceName,jdbcType=VARCHAR}, #{dgrmResourceName,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{hasStartFormKey,jdbcType=TINYINT}, ",
        "#{hasGraphicalNotation,jdbcType=TINYINT}, #{suspensionState,jdbcType=INTEGER}, ",
        "#{tenantId,jdbcType=VARCHAR})"
    })
    int insert(ReProcdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbggenerated
     */
    int insertSelective(ReProcdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, CATEGORY_, NAME_, KEY_, VERSION_, DEPLOYMENT_ID_, RESOURCE_NAME_, ",
        "DGRM_RESOURCE_NAME_, DESCRIPTION_, HAS_START_FORM_KEY_, HAS_GRAPHICAL_NOTATION_, ",
        "SUSPENSION_STATE_, TENANT_ID_",
        "from act_re_procdef",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReProcdef selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReProcdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbggenerated
     */
    @Update({
        "update act_re_procdef",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "CATEGORY_ = #{category,jdbcType=VARCHAR},",
          "NAME_ = #{name,jdbcType=VARCHAR},",
          "KEY_ = #{key,jdbcType=VARCHAR},",
          "VERSION_ = #{version,jdbcType=INTEGER},",
          "DEPLOYMENT_ID_ = #{deploymentId,jdbcType=VARCHAR},",
          "RESOURCE_NAME_ = #{resourceName,jdbcType=VARCHAR},",
          "DGRM_RESOURCE_NAME_ = #{dgrmResourceName,jdbcType=VARCHAR},",
          "DESCRIPTION_ = #{description,jdbcType=VARCHAR},",
          "HAS_START_FORM_KEY_ = #{hasStartFormKey,jdbcType=TINYINT},",
          "HAS_GRAPHICAL_NOTATION_ = #{hasGraphicalNotation,jdbcType=TINYINT},",
          "SUSPENSION_STATE_ = #{suspensionState,jdbcType=INTEGER},",
          "TENANT_ID_ = #{tenantId,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReProcdef record);
}