package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Resources;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_resources",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_resources (id, res_name, ",
        "parent_id, res_fid, ",
        "res_fname, res_type, ",
        "res_url, res_icon, ",
        "res_level, is_hidden, ",
        "is_remove, comments, ",
        "create_time, create_user, ",
        "update_time, update_user)",
        "values (#{id,jdbcType=VARCHAR}, #{resName,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=VARCHAR}, #{resFid,jdbcType=VARCHAR}, ",
        "#{resFname,jdbcType=VARCHAR}, #{resType,jdbcType=VARCHAR}, ",
        "#{resUrl,jdbcType=VARCHAR}, #{resIcon,jdbcType=VARCHAR}, ",
        "#{resLevel,jdbcType=INTEGER}, #{isHidden,jdbcType=CHAR}, ",
        "#{isRemove,jdbcType=CHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR})"
    })
    int insert(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    int insertSelective(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, res_name, parent_id, res_fid, res_fname, res_type, res_url, res_icon, res_level, ",
        "is_hidden, is_remove, comments, create_time, create_user, update_time, update_user",
        "from sys_resources",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Resources selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    @Update({
        "update sys_resources",
        "set res_name = #{resName,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=VARCHAR},",
          "res_fid = #{resFid,jdbcType=VARCHAR},",
          "res_fname = #{resFname,jdbcType=VARCHAR},",
          "res_type = #{resType,jdbcType=VARCHAR},",
          "res_url = #{resUrl,jdbcType=VARCHAR},",
          "res_icon = #{resIcon,jdbcType=VARCHAR},",
          "res_level = #{resLevel,jdbcType=INTEGER},",
          "is_hidden = #{isHidden,jdbcType=CHAR},",
          "is_remove = #{isRemove,jdbcType=CHAR},",
          "comments = #{comments,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Resources record);
}