package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.RoleRes;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RoleResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_res
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sys_role_res",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_res
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sys_role_res (id, role_id, ",
        "res_id)",
        "values (#{id,jdbcType=INTEGER}, #{roleId,jdbcType=VARCHAR}, ",
        "#{resId,jdbcType=VARCHAR})"
    })
    int insert(RoleRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_res
     *
     * @mbggenerated
     */
    int insertSelective(RoleRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_res
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, role_id, res_id",
        "from sys_role_res",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    RoleRes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_res
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_res
     *
     * @mbggenerated
     */
    @Update({
        "update sys_role_res",
        "set role_id = #{roleId,jdbcType=VARCHAR},",
          "res_id = #{resId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RoleRes record);
}