package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.RuEventSubscr;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RuEventSubscrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_ru_event_subscr",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_ru_event_subscr (ID_, REV_, ",
        "EVENT_TYPE_, EVENT_NAME_, ",
        "EXECUTION_ID_, PROC_INST_ID_, ",
        "ACTIVITY_ID_, CONFIGURATION_, ",
        "CREATED_, PROC_DEF_ID_, ",
        "TENANT_ID_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{eventType,jdbcType=VARCHAR}, #{eventName,jdbcType=VARCHAR}, ",
        "#{executionId,jdbcType=VARCHAR}, #{procInstId,jdbcType=VARCHAR}, ",
        "#{activityId,jdbcType=VARCHAR}, #{configuration,jdbcType=VARCHAR}, ",
        "#{created,jdbcType=TIMESTAMP}, #{procDefId,jdbcType=VARCHAR}, ",
        "#{tenantId,jdbcType=VARCHAR})"
    })
    int insert(RuEventSubscr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbggenerated
     */
    int insertSelective(RuEventSubscr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, EVENT_TYPE_, EVENT_NAME_, EXECUTION_ID_, PROC_INST_ID_, ACTIVITY_ID_, ",
        "CONFIGURATION_, CREATED_, PROC_DEF_ID_, TENANT_ID_",
        "from act_ru_event_subscr",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    RuEventSubscr selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RuEventSubscr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbggenerated
     */
    @Update({
        "update act_ru_event_subscr",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "EVENT_TYPE_ = #{eventType,jdbcType=VARCHAR},",
          "EVENT_NAME_ = #{eventName,jdbcType=VARCHAR},",
          "EXECUTION_ID_ = #{executionId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "ACTIVITY_ID_ = #{activityId,jdbcType=VARCHAR},",
          "CONFIGURATION_ = #{configuration,jdbcType=VARCHAR},",
          "CREATED_ = #{created,jdbcType=TIMESTAMP},",
          "PROC_DEF_ID_ = #{procDefId,jdbcType=VARCHAR},",
          "TENANT_ID_ = #{tenantId,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RuEventSubscr record);
}