package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.RuIdentitylink;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RuIdentitylinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_ru_identitylink",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_ru_identitylink (ID_, REV_, ",
        "GROUP_ID_, TYPE_, USER_ID_, ",
        "TASK_ID_, PROC_INST_ID_, ",
        "PROC_DEF_ID_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{groupId,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{taskId,jdbcType=VARCHAR}, #{procInstId,jdbcType=VARCHAR}, ",
        "#{procDefId,jdbcType=VARCHAR})"
    })
    int insert(RuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbggenerated
     */
    int insertSelective(RuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, GROUP_ID_, TYPE_, USER_ID_, TASK_ID_, PROC_INST_ID_, PROC_DEF_ID_",
        "from act_ru_identitylink",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    RuIdentitylink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RuIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_identitylink
     *
     * @mbggenerated
     */
    @Update({
        "update act_ru_identitylink",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "GROUP_ID_ = #{groupId,jdbcType=VARCHAR},",
          "TYPE_ = #{type,jdbcType=VARCHAR},",
          "USER_ID_ = #{userId,jdbcType=VARCHAR},",
          "TASK_ID_ = #{taskId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "PROC_DEF_ID_ = #{procDefId,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RuIdentitylink record);
}