package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.RuTask;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RuTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbggenerated
     */
    @Delete({
        "delete from act_ru_task",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbggenerated
     */
    @Insert({
        "insert into act_ru_task (ID_, REV_, ",
        "EXECUTION_ID_, PROC_INST_ID_, ",
        "PROC_DEF_ID_, NAME_, ",
        "PARENT_TASK_ID_, DESCRIPTION_, ",
        "TASK_DEF_KEY_, OWNER_, ",
        "ASSIGNEE_, DELEGATION_, ",
        "PRIORITY_, CREATE_TIME_, ",
        "DUE_DATE_, CATEGORY_, ",
        "SUSPENSION_STATE_, TENANT_ID_, ",
        "FORM_KEY_)",
        "values (#{id,jdbcType=VARCHAR}, #{rev,jdbcType=INTEGER}, ",
        "#{executionId,jdbcType=VARCHAR}, #{procInstId,jdbcType=VARCHAR}, ",
        "#{procDefId,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{parentTaskId,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{taskDefKey,jdbcType=VARCHAR}, #{owner,jdbcType=VARCHAR}, ",
        "#{assignee,jdbcType=VARCHAR}, #{delegation,jdbcType=VARCHAR}, ",
        "#{priority,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{dueDate,jdbcType=TIMESTAMP}, #{category,jdbcType=VARCHAR}, ",
        "#{suspensionState,jdbcType=INTEGER}, #{tenantId,jdbcType=VARCHAR}, ",
        "#{formKey,jdbcType=VARCHAR})"
    })
    int insert(RuTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbggenerated
     */
    int insertSelective(RuTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID_, REV_, EXECUTION_ID_, PROC_INST_ID_, PROC_DEF_ID_, NAME_, PARENT_TASK_ID_, ",
        "DESCRIPTION_, TASK_DEF_KEY_, OWNER_, ASSIGNEE_, DELEGATION_, PRIORITY_, CREATE_TIME_, ",
        "DUE_DATE_, CATEGORY_, SUSPENSION_STATE_, TENANT_ID_, FORM_KEY_",
        "from act_ru_task",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    RuTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RuTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbggenerated
     */
    @Update({
        "update act_ru_task",
        "set REV_ = #{rev,jdbcType=INTEGER},",
          "EXECUTION_ID_ = #{executionId,jdbcType=VARCHAR},",
          "PROC_INST_ID_ = #{procInstId,jdbcType=VARCHAR},",
          "PROC_DEF_ID_ = #{procDefId,jdbcType=VARCHAR},",
          "NAME_ = #{name,jdbcType=VARCHAR},",
          "PARENT_TASK_ID_ = #{parentTaskId,jdbcType=VARCHAR},",
          "DESCRIPTION_ = #{description,jdbcType=VARCHAR},",
          "TASK_DEF_KEY_ = #{taskDefKey,jdbcType=VARCHAR},",
          "OWNER_ = #{owner,jdbcType=VARCHAR},",
          "ASSIGNEE_ = #{assignee,jdbcType=VARCHAR},",
          "DELEGATION_ = #{delegation,jdbcType=VARCHAR},",
          "PRIORITY_ = #{priority,jdbcType=INTEGER},",
          "CREATE_TIME_ = #{createTime,jdbcType=TIMESTAMP},",
          "DUE_DATE_ = #{dueDate,jdbcType=TIMESTAMP},",
          "CATEGORY_ = #{category,jdbcType=VARCHAR},",
          "SUSPENSION_STATE_ = #{suspensionState,jdbcType=INTEGER},",
          "TENANT_ID_ = #{tenantId,jdbcType=VARCHAR},",
          "FORM_KEY_ = #{formKey,jdbcType=VARCHAR}",
        "where ID_ = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RuTask record);
}