package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Sequence;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sequence
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_sequence",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sequence
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_sequence (id, name, ",
        "current_value, _increment, ",
        "pre, _format, org_id)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{currentValue,jdbcType=VARCHAR}, #{increment,jdbcType=INTEGER}, ",
        "#{pre,jdbcType=VARCHAR}, #{format,jdbcType=VARCHAR}, #{orgId,jdbcType=VARCHAR})"
    })
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sequence
     *
     * @mbggenerated
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sequence
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, current_value, _increment, pre, _format, org_id",
        "from tb_sequence",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Sequence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sequence
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sequence
     *
     * @mbggenerated
     */
    @Update({
        "update tb_sequence",
        "set name = #{name,jdbcType=VARCHAR},",
          "current_value = #{currentValue,jdbcType=VARCHAR},",
          "_increment = #{increment,jdbcType=INTEGER},",
          "pre = #{pre,jdbcType=VARCHAR},",
          "_format = #{format,jdbcType=VARCHAR},",
          "org_id = #{orgId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Sequence record);
}