package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Sfood;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SfoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sfood
     *
     * @mbggenerated
     */
    @Delete({
        "delete from w_sfood",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sfood
     *
     * @mbggenerated
     */
    @Insert({
        "insert into w_sfood (uuid, food_name, ",
        "food_code, food_type, ",
        "food_price, food_origin, ",
        "food_number, food_exp, ",
        "food_pic, Is_Active, ",
        "CREATE_DT, CREATE_OP, ",
        "CREATE_PG, UPDATE_DT, ",
        "UPDATE_OP, UPDATE_PG)",
        "values (#{uuid,jdbcType=VARCHAR}, #{foodName,jdbcType=VARCHAR}, ",
        "#{foodCode,jdbcType=VARCHAR}, #{foodType,jdbcType=CHAR}, ",
        "#{foodPrice,jdbcType=DECIMAL}, #{foodOrigin,jdbcType=VARCHAR}, ",
        "#{foodNumber,jdbcType=INTEGER},#{foodExp,jdbcType=VARCHAR},",
        "#{foodPic,jdbcType=VARCHAR}, #{isActive,jdbcType=VARCHAR}, ",
        "#{createDt,jdbcType=VARCHAR}, #{createOp,jdbcType=VARCHAR}, ",
        "#{createPg,jdbcType=VARCHAR}, #{updateDt,jdbcType=VARCHAR}, ",
        "#{updateOp,jdbcType=VARCHAR}, #{updatePg,jdbcType=VARCHAR})"
    })
    int insert(Sfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sfood
     *
     * @mbggenerated
     */
    int insertSelective(Sfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sfood
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "uuid, food_name, food_code, food_type, food_price, food_number, food_origin, food_exp, food_pic, Is_Active, ",
        "CREATE_DT, CREATE_OP, CREATE_PG, UPDATE_DT, UPDATE_OP, UPDATE_PG",
        "from w_sfood",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Sfood selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sfood
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sfood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_sfood
     *
     * @mbggenerated
     */
    @Update({
        "update w_sfood",
        "set food_name = #{foodName,jdbcType=VARCHAR},",
          "food_code = #{foodCode,jdbcType=VARCHAR},",
          "food_type = #{foodType,jdbcType=CHAR},",
          "food_price = #{foodPrice,jdbcType=DECIMAL},",
          "food_number = #{foodNumber,jdbcType=INTEGER},",
          "food_origin = #{foodOrigin,jdbcType=VARCHAR},",
          "food_exp = #{foodExp,jdbcType=VARCHAR},",
          "food_pic = #{foodPic,jdbcType=VARCHAR},",
          "Is_Active = #{isActive,jdbcType=VARCHAR},",
          "CREATE_DT = #{createDt,jdbcType=TIMESTAMP},",
          "CREATE_OP = #{createOp,jdbcType=VARCHAR},",
          "CREATE_PG = #{createPg,jdbcType=VARCHAR},",
          "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
          "UPDATE_OP = #{updateOp,jdbcType=VARCHAR},",
          "UPDATE_PG = #{updatePg,jdbcType=VARCHAR}",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Sfood record);
}