package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Students;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface StudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_students
     *
     * @mbggenerated
     */
    @Delete({
        "delete from s_students",
        "where stu_id = #{stuId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_students
     *
     * @mbggenerated
     */
    @Insert({
        "insert into s_students (stu_id, stu_name, ",
        "stu_major, cou_name, ",
        "cou_type, stu_gra, ",
        "gra_max, gra_min, ",
        "stu_sex, instruction)",
        "values (#{stuId,jdbcType=VARCHAR}, #{stuName,jdbcType=VARCHAR}, ",
        "#{stuMajor,jdbcType=VARCHAR}, #{couName,jdbcType=VARCHAR}, ",
        "#{couType,jdbcType=VARCHAR}, #{stuGra,jdbcType=INTEGER}, ",
        "#{graMax,jdbcType=INTEGER}, #{graMin,jdbcType=INTEGER}, ",
        "#{stuSex,jdbcType=CHAR}, #{instruction,jdbcType=VARCHAR})"
    })
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_students
     *
     * @mbggenerated
     */
    int insertSelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_students
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "stu_id, stu_name, stu_major, cou_name, cou_type, stu_gra, gra_max, gra_min, ",
        "stu_sex, instruction",
        "from s_students",
        "where stu_id = #{stuId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Students selectByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_students
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_students
     *
     * @mbggenerated
     */
    @Update({
        "update s_students",
        "set stu_name = #{stuName,jdbcType=VARCHAR},",
          "stu_major = #{stuMajor,jdbcType=VARCHAR},",
          "cou_name = #{couName,jdbcType=VARCHAR},",
          "cou_type = #{couType,jdbcType=VARCHAR},",
          "stu_gra = #{stuGra,jdbcType=INTEGER},",
          "gra_max = #{graMax,jdbcType=INTEGER},",
          "gra_min = #{graMin,jdbcType=INTEGER},",
          "stu_sex = #{stuSex,jdbcType=CHAR},",
          "instruction = #{instruction,jdbcType=VARCHAR}",
        "where stu_id = #{stuId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Students record);
}