package com.ltkj.app.common.dao;

import com.ltkj.app.common.model.Tuser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_user",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_user (uuid, u_name, ",
        "u_password, u_sex, u_age, ",
        "u_class, CREATE_DT, ",
        "CREATE_OP, CREATE_PG, ",
        "UPDATE_DT, UPDATE_OP, ",
        "UPDATE_PG, VERSION)",
        "values (#{uuid,jdbcType=VARCHAR}, #{uName,jdbcType=VARCHAR}, ",
        "#{uPassword,jdbcType=VARCHAR}, #{uSex,jdbcType=CHAR}, #{uAge,jdbcType=VARCHAR}, ",
        "#{uClass,jdbcType=INTEGER}, #{createDt,jdbcType=TIMESTAMP}, ",
        "#{createOp,jdbcType=VARCHAR}, #{createPg,jdbcType=VARCHAR}, ",
        "#{updateDt,jdbcType=TIMESTAMP}, #{updateOp,jdbcType=VARCHAR}, ",
        "#{updatePg,jdbcType=VARCHAR}, #{version,jdbcType=INTEGER})"
    })
    int insert(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insertSelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "uuid, u_name, u_password, u_sex, u_age, u_class, CREATE_DT, CREATE_OP, CREATE_PG, ",
        "UPDATE_DT, UPDATE_OP, UPDATE_PG, VERSION",
        "from t_user",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Tuser selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    @Update({
        "update t_user",
        "set u_name = #{uName,jdbcType=VARCHAR},",
          "u_password = #{uPassword,jdbcType=VARCHAR},",
          "u_sex = #{uSex,jdbcType=CHAR},",
          "u_age = #{uAge,jdbcType=VARCHAR},",
          "u_class = #{uClass,jdbcType=INTEGER},",
          "CREATE_DT = #{createDt,jdbcType=TIMESTAMP},",
          "CREATE_OP = #{createOp,jdbcType=VARCHAR},",
          "CREATE_PG = #{createPg,jdbcType=VARCHAR},",
          "UPDATE_DT = #{updateDt,jdbcType=TIMESTAMP},",
          "UPDATE_OP = #{updateOp,jdbcType=VARCHAR},",
          "UPDATE_PG = #{updatePg,jdbcType=VARCHAR},",
          "VERSION = #{version,jdbcType=INTEGER}",
        "where uuid = #{uuid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Tuser record);
}